// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Account - An account in the ledger, identified by its address
type Account struct {
	// The account address, a colon-separated segmented path such as users:001
	Address string `json:"address"`
	// Arbitrary key/value pairs attached to the account
	Metadata map[string]string `json:"metadata"`
	// Volumes per asset for a single account
	Volumes map[string]Volume `json:"volumes,omitempty"`
	// Volumes per asset for a single account
	EffectiveVolumes map[string]Volume `json:"effectiveVolumes,omitempty"`
}

func (o *Account) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *Account) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *Account) GetVolumes() map[string]Volume {
	if o == nil {
		return nil
	}
	return o.Volumes
}

func (o *Account) GetEffectiveVolumes() map[string]Volume {
	if o == nil {
		return nil
	}
	return o.EffectiveVolumes
}
