// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountResponse struct {
	// An account in the ledger, identified by its address
	Data Account `json:"data"`
}

func (o *AccountResponse) GetData() Account {
	if o == nil {
		return Account{}
	}
	return o.Data
}
