// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActivityRevertTransaction - Arguments for the activity that reverts a ledger transaction
type ActivityRevertTransaction struct {
	// Name of the ledger holding the transaction
	Ledger string `json:"ledger"`
	// Identifier of the transaction to revert
	ID string `json:"id"`
}

func (o *ActivityRevertTransaction) GetLedger() string {
	if o == nil {
		return ""
	}
	return o.Ledger
}

func (o *ActivityRevertTransaction) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
