// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActivityGetAccountOutput struct {
	Data Account `json:"data"`
}

func (o *ActivityGetAccountOutput) GetData() Account {
	if o == nil {
		return Account{}
	}
	return o.Data
}
