// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActivityCreditWallet struct {
	ID   *string              `json:"id,omitempty"`
	Data *CreditWalletRequest `json:"data,omitempty"`
}

func (o *ActivityCreditWallet) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ActivityCreditWallet) GetData() *CreditWalletRequest {
	if o == nil {
		return nil
	}
	return o.Data
}
