// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActivityCreditWallet - Arguments for the activity that credits a wallet
type ActivityCreditWallet struct {
	// Identifier of the wallet to credit
	ID *string `json:"id,omitempty"`
	// A credit to apply to a wallet
	Data *CreditWalletRequest `json:"data,omitempty"`
}

func (o *ActivityCreditWallet) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ActivityCreditWallet) GetData() *CreditWalletRequest {
	if o == nil {
		return nil
	}
	return o.Data
}
