// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActivityAddAccountMetadata - Arguments for the activity that sets metadata on a ledger account
type ActivityAddAccountMetadata struct {
	// Address of the ledger account to update
	ID string `json:"id"`
	// Name of the ledger holding the account
	Ledger string `json:"ledger"`
	// Metadata to set on the account
	Metadata map[string]string `json:"metadata"`
}

func (o *ActivityAddAccountMetadata) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ActivityAddAccountMetadata) GetLedger() string {
	if o == nil {
		return ""
	}
	return o.Ledger
}

func (o *ActivityAddAccountMetadata) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}
