// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActivityCreateTransaction - Arguments for the activity that writes a transaction to a ledger
type ActivityCreateTransaction struct {
	// Name of the ledger to write the transaction to
	Ledger *string `json:"ledger,omitempty"`
	// A transaction to write to a ledger
	Data *PostTransaction `json:"data,omitempty"`
}

func (o *ActivityCreateTransaction) GetLedger() *string {
	if o == nil {
		return nil
	}
	return o.Ledger
}

func (o *ActivityCreateTransaction) GetData() *PostTransaction {
	if o == nil {
		return nil
	}
	return o.Data
}
