// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActivityVoidHold - Arguments for the activity that releases a wallet hold
type ActivityVoidHold struct {
	// Identifier of the hold to release
	ID string `json:"id"`
}

func (o *ActivityVoidHold) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
