// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActivityDebitWallet struct {
	ID   *string             `json:"id,omitempty"`
	Data *DebitWalletRequest `json:"data,omitempty"`
}

func (o *ActivityDebitWallet) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ActivityDebitWallet) GetData() *DebitWalletRequest {
	if o == nil {
		return nil
	}
	return o.Data
}
