// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActivityConfirmHold - Arguments for the activity that confirms a wallet hold
type ActivityConfirmHold struct {
	// Identifier of the hold to confirm
	ID string `json:"id"`
}

func (o *ActivityConfirmHold) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
