// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActivityGetPaymentOutput struct {
	Data Payment `json:"data"`
}

func (o *ActivityGetPaymentOutput) GetData() Payment {
	if o == nil {
		return Payment{}
	}
	return o.Data
}
