// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActivityCreateTransaction struct {
	Ledger *string          `json:"ledger,omitempty"`
	Data   *PostTransaction `json:"data,omitempty"`
}

func (o *ActivityCreateTransaction) GetLedger() *string {
	if o == nil {
		return nil
	}
	return o.Ledger
}

func (o *ActivityCreateTransaction) GetData() *PostTransaction {
	if o == nil {
		return nil
	}
	return o.Data
}
