// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/flows/pkg/client/internal/utils"
	"math/big"
)

// ActivityCreateTransferInitiationType - Type of transfer initiation:
// - TRANSFER: Internal to internal account transfer
// - PAYOUT: Internal to external account payout
type ActivityCreateTransferInitiationType string

const (
	ActivityCreateTransferInitiationTypeTransfer ActivityCreateTransferInitiationType = "TRANSFER"
	ActivityCreateTransferInitiationTypePayout   ActivityCreateTransferInitiationType = "PAYOUT"
)

func (e ActivityCreateTransferInitiationType) ToPointer() *ActivityCreateTransferInitiationType {
	return &e
}
func (e *ActivityCreateTransferInitiationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TRANSFER":
		fallthrough
	case "PAYOUT":
		*e = ActivityCreateTransferInitiationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ActivityCreateTransferInitiationType: %v", v)
	}
}

// ActivityCreateTransferInitiationMetadata - A set of key/value pairs that you can attach to a transfer object. It can be useful for storing additional information about the transfer in a structured format.
type ActivityCreateTransferInitiationMetadata struct {
}

type ActivityCreateTransferInitiation struct {
	ConnectorID *string `json:"connectorID,omitempty"`
	// Payment service provider name (e.g., stripe, wise, mangopay).
	// Validated by the Payments service based on installed connectors.
	//
	Provider *string  `json:"provider,omitempty"`
	Amount   *big.Int `json:"amount,omitempty"`
	Asset    *string  `json:"asset,omitempty"`
	// Destination account ID
	Destination *string `json:"destination,omitempty"`
	// Source account ID (required for TRANSFER type)
	Source *string `json:"source,omitempty"`
	// Type of transfer initiation:
	// - TRANSFER: Internal to internal account transfer
	// - PAYOUT: Internal to external account payout
	//
	Type *ActivityCreateTransferInitiationType `default:"TRANSFER" json:"type"`
	// Description for the transfer initiation
	Description       *string `json:"description,omitempty"`
	WaitingValidation *bool   `default:"false" json:"waitingValidation"`
	// A set of key/value pairs that you can attach to a transfer object. It can be useful for storing additional information about the transfer in a structured format.
	//
	Metadata *ActivityCreateTransferInitiationMetadata `json:"metadata,omitempty"`
}

func (a ActivityCreateTransferInitiation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActivityCreateTransferInitiation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ActivityCreateTransferInitiation) GetConnectorID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectorID
}

func (o *ActivityCreateTransferInitiation) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *ActivityCreateTransferInitiation) GetAmount() *big.Int {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *ActivityCreateTransferInitiation) GetAsset() *string {
	if o == nil {
		return nil
	}
	return o.Asset
}

func (o *ActivityCreateTransferInitiation) GetDestination() *string {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *ActivityCreateTransferInitiation) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *ActivityCreateTransferInitiation) GetType() *ActivityCreateTransferInitiationType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *ActivityCreateTransferInitiation) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ActivityCreateTransferInitiation) GetWaitingValidation() *bool {
	if o == nil {
		return nil
	}
	return o.WaitingValidation
}

func (o *ActivityCreateTransferInitiation) GetMetadata() *ActivityCreateTransferInitiationMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}
