// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActivityDebitWallet - Arguments for the activity that debits a wallet
type ActivityDebitWallet struct {
	// Identifier of the wallet to debit
	ID *string `json:"id,omitempty"`
	// A debit to apply to a wallet
	Data *DebitWalletRequest `json:"data,omitempty"`
}

func (o *ActivityDebitWallet) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ActivityDebitWallet) GetData() *DebitWalletRequest {
	if o == nil {
		return nil
	}
	return o.Data
}
