// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActivityGetAccount - Arguments for the activity that reads a ledger account
type ActivityGetAccount struct {
	// Address of the ledger account to read
	ID string `json:"id"`
	// Name of the ledger holding the account
	Ledger string `json:"ledger"`
}

func (o *ActivityGetAccount) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ActivityGetAccount) GetLedger() string {
	if o == nil {
		return ""
	}
	return o.Ledger
}
