// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActivityRevertTransactionOutput struct {
	Data Transaction `json:"data"`
}

func (o *ActivityRevertTransactionOutput) GetData() Transaction {
	if o == nil {
		return Transaction{}
	}
	return o.Data
}
