// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActivityCreateTransactionOutput struct {
	Data Transaction `json:"data"`
}

func (o *ActivityCreateTransactionOutput) GetData() Transaction {
	if o == nil {
		return Transaction{}
	}
	return o.Data
}
