// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// CreditWalletRequest - A credit to apply to a wallet
type CreditWalletRequest struct {
	// An amount together with the asset it is denominated in
	Amount Monetary `json:"amount"`
	// Metadata associated with the wallet.
	Metadata map[string]string `json:"metadata"`
	// Optional caller-supplied identifier used to deduplicate the credit
	Reference *string `json:"reference,omitempty"`
	// Where the funds come from
	Sources []Subject `json:"sources"`
	// The balance to credit
	Balance *string `json:"balance,omitempty"`
	// The transaction time to record on the resulting transaction. See [bi-temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

func (c CreditWalletRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditWalletRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreditWalletRequest) GetAmount() Monetary {
	if o == nil {
		return Monetary{}
	}
	return o.Amount
}

func (o *CreditWalletRequest) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *CreditWalletRequest) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *CreditWalletRequest) GetSources() []Subject {
	if o == nil {
		return []Subject{}
	}
	return o.Sources
}

func (o *CreditWalletRequest) GetBalance() *string {
	if o == nil {
		return nil
	}
	return o.Balance
}

func (o *CreditWalletRequest) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}
