// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetWorkflowInstanceHistoryStageResponse struct {
	// Per-activity history of a workflow stage
	Data []WorkflowInstanceHistoryStage `json:"data"`
}

func (o *GetWorkflowInstanceHistoryStageResponse) GetData() []WorkflowInstanceHistoryStage {
	if o == nil {
		return []WorkflowInstanceHistoryStage{}
	}
	return o.Data
}
