// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetWorkflowInstanceResponse struct {
	// One run of a workflow, tracking its per-stage progress
	Data WorkflowInstance `json:"data"`
}

func (o *GetWorkflowInstanceResponse) GetData() WorkflowInstance {
	if o == nil {
		return WorkflowInstance{}
	}
	return o.Data
}
