// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetWorkflowResponse struct {
	// A workflow definition and the stages it runs
	Data Workflow `json:"data"`
}

func (o *GetWorkflowResponse) GetData() Workflow {
	if o == nil {
		return Workflow{}
	}
	return o.Data
}
