// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetWorkflowInstanceHistoryResponse struct {
	// Per-stage history of a workflow run
	Data []WorkflowInstanceHistory `json:"data"`
}

func (o *GetWorkflowInstanceHistoryResponse) GetData() []WorkflowInstanceHistory {
	if o == nil {
		return []WorkflowInstanceHistory{}
	}
	return o.Data
}
