// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListTriggersOccurrencesResponse struct {
	// The trigger's occurrences
	Data []TriggerOccurrence `json:"data"`
}

func (o *ListTriggersOccurrencesResponse) GetData() []TriggerOccurrence {
	if o == nil {
		return []TriggerOccurrence{}
	}
	return o.Data
}
