// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListWorkflowsResponse struct {
	// The workflows defined on this stack
	Data []Workflow `json:"data"`
}

func (o *ListWorkflowsResponse) GetData() []Workflow {
	if o == nil {
		return []Workflow{}
	}
	return o.Data
}
