// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListTriggersResponse struct {
	// The triggers defined on this stack
	Data []Trigger `json:"data"`
}

func (o *ListTriggersResponse) GetData() []Trigger {
	if o == nil {
		return []Trigger{}
	}
	return o.Data
}
