// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Cursor struct {
	PageSize int64    `json:"pageSize"`
	HasMore  *bool    `json:"hasMore,omitempty"`
	Previous *string  `json:"previous,omitempty"`
	Next     *string  `json:"next,omitempty"`
	Data     []Wallet `json:"data"`
}

func (o *Cursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *Cursor) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}

func (o *Cursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *Cursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *Cursor) GetData() []Wallet {
	if o == nil {
		return []Wallet{}
	}
	return o.Data
}

type ListWalletsResponse struct {
	Cursor Cursor `json:"cursor"`
}

func (o *ListWalletsResponse) GetCursor() Cursor {
	if o == nil {
		return Cursor{}
	}
	return o.Cursor
}
