// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListTriggersResponse struct {
	Data     []Trigger `json:"data"`
	PageSize int64     `json:"pageSize"`
	HasMore  bool      `json:"hasMore"`
	Previous *string   `json:"previous,omitempty"`
	Next     *string   `json:"next,omitempty"`
}

func (o *ListTriggersResponse) GetData() []Trigger {
	if o == nil {
		return []Trigger{}
	}
	return o.Data
}

func (o *ListTriggersResponse) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *ListTriggersResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *ListTriggersResponse) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ListTriggersResponse) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}
