// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaymentMetadata struct {
	Key *string `json:"key,omitempty"`
}

func (o *PaymentMetadata) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}
