// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaymentMetadata - Arbitrary key/value pairs attached to a payment
type PaymentMetadata struct {
	// Metadata value carried by the payment
	Key *string `json:"key,omitempty"`
}

func (o *PaymentMetadata) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}
