// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"math/big"
	"openapi/internal/utils"
	"time"
)

type PaymentAdjustmentRaw struct {
}

type PaymentAdjustment struct {
	Status   PaymentStatus        `json:"status"`
	Amount   *big.Int             `json:"amount"`
	Date     time.Time            `json:"date"`
	Raw      PaymentAdjustmentRaw `json:"raw"`
	Absolute bool                 `json:"absolute"`
}

func (p PaymentAdjustment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentAdjustment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PaymentAdjustment) GetStatus() PaymentStatus {
	if o == nil {
		return PaymentStatus("")
	}
	return o.Status
}

func (o *PaymentAdjustment) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *PaymentAdjustment) GetDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Date
}

func (o *PaymentAdjustment) GetRaw() PaymentAdjustmentRaw {
	if o == nil {
		return PaymentAdjustmentRaw{}
	}
	return o.Raw
}

func (o *PaymentAdjustment) GetAbsolute() bool {
	if o == nil {
		return false
	}
	return o.Absolute
}
