// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"math/big"
	"openapi/internal/utils"
	"time"
)

// PaymentType - Direction of the payment
type PaymentType string

const (
	PaymentTypePayIn    PaymentType = "PAY-IN"
	PaymentTypePayout   PaymentType = "PAYOUT"
	PaymentTypeTransfer PaymentType = "TRANSFER"
	PaymentTypeOther    PaymentType = "OTHER"
)

func (e PaymentType) ToPointer() *PaymentType {
	return &e
}
func (e *PaymentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PAY-IN":
		fallthrough
	case "PAYOUT":
		fallthrough
	case "TRANSFER":
		fallthrough
	case "OTHER":
		*e = PaymentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentType: %v", v)
	}
}

// Scheme - Payment scheme or rail the payment travelled over
type Scheme string

const (
	SchemeVisa       Scheme = "visa"
	SchemeMastercard Scheme = "mastercard"
	SchemeAmex       Scheme = "amex"
	SchemeDiners     Scheme = "diners"
	SchemeDiscover   Scheme = "discover"
	SchemeJcb        Scheme = "jcb"
	SchemeUnionpay   Scheme = "unionpay"
	SchemeSepaDebit  Scheme = "sepa debit"
	SchemeSepaCredit Scheme = "sepa credit"
	SchemeSepa       Scheme = "sepa"
	SchemeApplePay   Scheme = "apple pay"
	SchemeGooglePay  Scheme = "google pay"
	SchemeA2a        Scheme = "a2a"
	SchemeAchDebit   Scheme = "ach debit"
	SchemeAch        Scheme = "ach"
	SchemeRtp        Scheme = "rtp"
	SchemeUnknown    Scheme = "unknown"
	SchemeOther      Scheme = "other"
)

func (e Scheme) ToPointer() *Scheme {
	return &e
}
func (e *Scheme) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "visa":
		fallthrough
	case "mastercard":
		fallthrough
	case "amex":
		fallthrough
	case "diners":
		fallthrough
	case "discover":
		fallthrough
	case "jcb":
		fallthrough
	case "unionpay":
		fallthrough
	case "sepa debit":
		fallthrough
	case "sepa credit":
		fallthrough
	case "sepa":
		fallthrough
	case "apple pay":
		fallthrough
	case "google pay":
		fallthrough
	case "a2a":
		fallthrough
	case "ach debit":
		fallthrough
	case "ach":
		fallthrough
	case "rtp":
		fallthrough
	case "unknown":
		fallthrough
	case "other":
		*e = Scheme(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Scheme: %v", v)
	}
}

// Raw - The provider's original payload, passed through untouched
type Raw struct {
}

// Payment - A payment observed or initiated through a connector
type Payment struct {
	// Unique identifier of the payment
	ID string `json:"id"`
	// Identifier the payment carries at the provider
	Reference string `json:"reference"`
	// Identifier of the account the funds left
	SourceAccountID string `json:"sourceAccountID"`
	// Identifier of the account the funds reached
	DestinationAccountID string `json:"destinationAccountID"`
	// Identifier of the connector that produced the payment
	ConnectorID string `json:"connectorID"`
	// The payment provider behind a connector
	Provider *Connector `json:"provider,omitempty"`
	// Direction of the payment
	Type PaymentType `json:"type"`
	// Where a payment stands in its lifecycle
	Status PaymentStatus `json:"status"`
	// Amount the payment was created with, before any adjustment
	InitialAmount *big.Int `json:"initialAmount"`
	// Payment scheme or rail the payment travelled over
	Scheme Scheme `json:"scheme"`
	// Asset the payment is denominated in
	Asset string `json:"asset"`
	// When the payment was created
	CreatedAt time.Time `json:"createdAt"`
	// The provider's original payload, passed through untouched
	Raw *Raw `json:"raw"`
	// Successive changes to the payment's amount and status
	Adjustments []PaymentAdjustment `json:"adjustments"`
	// Arbitrary key/value pairs attached to a payment
	Metadata *PaymentMetadata `json:"metadata"`
}

func (p Payment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Payment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Payment) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Payment) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *Payment) GetSourceAccountID() string {
	if o == nil {
		return ""
	}
	return o.SourceAccountID
}

func (o *Payment) GetDestinationAccountID() string {
	if o == nil {
		return ""
	}
	return o.DestinationAccountID
}

func (o *Payment) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *Payment) GetProvider() *Connector {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *Payment) GetType() PaymentType {
	if o == nil {
		return PaymentType("")
	}
	return o.Type
}

func (o *Payment) GetStatus() PaymentStatus {
	if o == nil {
		return PaymentStatus("")
	}
	return o.Status
}

func (o *Payment) GetInitialAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.InitialAmount
}

func (o *Payment) GetScheme() Scheme {
	if o == nil {
		return Scheme("")
	}
	return o.Scheme
}

func (o *Payment) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *Payment) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Payment) GetRaw() *Raw {
	if o == nil {
		return nil
	}
	return o.Raw
}

func (o *Payment) GetAdjustments() []PaymentAdjustment {
	if o == nil {
		return []PaymentAdjustment{}
	}
	return o.Adjustments
}

func (o *Payment) GetMetadata() *PaymentMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}
