// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// Script - A Numscript program executed to produce the postings. Mutually exclusive with postings
type Script struct {
	Plain string         `json:"plain"`
	Vars  map[string]any `json:"vars,omitempty"`
}

func (o *Script) GetPlain() string {
	if o == nil {
		return ""
	}
	return o.Plain
}

func (o *Script) GetVars() map[string]any {
	if o == nil {
		return nil
	}
	return o.Vars
}

// PostTransaction - A transaction to write to a ledger
type PostTransaction struct {
	// The transaction time to record, letting you backdate or postdate the transaction. See [bi-temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Fund movements to apply. Mutually exclusive with script
	Postings []Posting `json:"postings,omitempty"`
	// A Numscript program executed to produce the postings. Mutually exclusive with postings
	Script *Script `json:"script,omitempty"`
	// Optional caller-supplied identifier, unique within the ledger, used to deduplicate transactions
	Reference *string `json:"reference,omitempty"`
	// Arbitrary key/value pairs attached to the resource
	Metadata map[string]string `json:"metadata"`
}

func (p PostTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PostTransaction) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}

func (o *PostTransaction) GetPostings() []Posting {
	if o == nil {
		return nil
	}
	return o.Postings
}

func (o *PostTransaction) GetScript() *Script {
	if o == nil {
		return nil
	}
	return o.Script
}

func (o *PostTransaction) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *PostTransaction) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}
