// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type Script struct {
	Plain string         `json:"plain"`
	Vars  map[string]any `json:"vars,omitempty"`
}

func (o *Script) GetPlain() string {
	if o == nil {
		return ""
	}
	return o.Plain
}

func (o *Script) GetVars() map[string]any {
	if o == nil {
		return nil
	}
	return o.Vars
}

type PostTransaction struct {
	Timestamp *time.Time        `json:"timestamp,omitempty"`
	Postings  []Posting         `json:"postings,omitempty"`
	Script    *Script           `json:"script,omitempty"`
	Reference *string           `json:"reference,omitempty"`
	Metadata  map[string]string `json:"metadata"`
}

func (p PostTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PostTransaction) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}

func (o *PostTransaction) GetPostings() []Posting {
	if o == nil {
		return nil
	}
	return o.Postings
}

func (o *PostTransaction) GetScript() *Script {
	if o == nil {
		return nil
	}
	return o.Script
}

func (o *PostTransaction) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *PostTransaction) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}
