// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReadTriggerResponse struct {
	// A rule that starts a workflow when a matching event arrives
	Data Trigger `json:"data"`
}

func (o *ReadTriggerResponse) GetData() Trigger {
	if o == nil {
		return Trigger{}
	}
	return o.Data
}
