// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RevertTransactionResponse struct {
	// A transaction recorded in the ledger, carrying its postings and metadata
	Data Transaction `json:"data"`
}

func (o *RevertTransactionResponse) GetData() Transaction {
	if o == nil {
		return Transaction{}
	}
	return o.Data
}
