// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/flows/pkg/client/internal/utils"
)

type StageSendSourceAccount struct {
	ID     string  `json:"id"`
	Ledger *string `json:"ledger,omitempty"`
	// Account used when this ledger account interacts with external systems (payments, cross-ledger).
	// - As SOURCE going to payment: funds are sent to this account (e.g., "liabilities:payouts-pending")
	// - As DESTINATION from payment: funds come from this account (e.g., "assets:stripe:incoming")
	// - For cross-ledger transfers: replaces "world" on both sides
	//
	ThroughAccount *string `default:"world" json:"throughAccount"`
	// Enables unbounded overdraft on the throughAccount when set to true.
	// This is useful when the throughAccount represents a liability or bridge account
	// that needs to go negative (e.g., "liabilities:payouts-pending").
	// Only applies when throughAccount is not "world" (which already has unbounded overdraft).
	//
	AllowOverdraft *bool `default:"false" json:"allowOverdraft"`
}

func (s StageSendSourceAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StageSendSourceAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *StageSendSourceAccount) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *StageSendSourceAccount) GetLedger() *string {
	if o == nil {
		return nil
	}
	return o.Ledger
}

func (o *StageSendSourceAccount) GetThroughAccount() *string {
	if o == nil {
		return nil
	}
	return o.ThroughAccount
}

func (o *StageSendSourceAccount) GetAllowOverdraft() *bool {
	if o == nil {
		return nil
	}
	return o.AllowOverdraft
}
