// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StageSendSource struct {
	Wallet  *StageSendSourceWallet  `json:"wallet,omitempty"`
	Account *StageSendSourceAccount `json:"account,omitempty"`
	Payment *StageSendSourcePayment `json:"payment,omitempty"`
}

func (o *StageSendSource) GetWallet() *StageSendSourceWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}

func (o *StageSendSource) GetAccount() *StageSendSourceAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *StageSendSource) GetPayment() *StageSendSourcePayment {
	if o == nil {
		return nil
	}
	return o.Payment
}
