// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// StageSendSource - Where a send stage takes the funds from
type StageSendSource struct {
	// Take the funds from a wallet
	Wallet *StageSendSourceWallet `json:"wallet,omitempty"`
	// Take the funds from a ledger account
	Account *StageSendSourceAccount `json:"account,omitempty"`
	// Take the funds from a payment
	Payment *StageSendSourcePayment `json:"payment,omitempty"`
}

func (o *StageSendSource) GetWallet() *StageSendSourceWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}

func (o *StageSendSource) GetAccount() *StageSendSourceAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *StageSendSource) GetPayment() *StageSendSourcePayment {
	if o == nil {
		return nil
	}
	return o.Payment
}
