// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// StageSendDestination - Where a send stage puts the funds
type StageSendDestination struct {
	// Send the funds to a wallet
	Wallet *StageSendSourceWallet `json:"wallet,omitempty"`
	// Send the funds to a ledger account
	Account *StageSendSourceAccount `json:"account,omitempty"`
	// Send the funds to a payment
	Payment *StageSendDestinationPayment `json:"payment,omitempty"`
}

func (o *StageSendDestination) GetWallet() *StageSendSourceWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}

func (o *StageSendDestination) GetAccount() *StageSendSourceAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *StageSendDestination) GetPayment() *StageSendDestinationPayment {
	if o == nil {
		return nil
	}
	return o.Payment
}
