// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type StageSend struct {
	// An amount together with the asset it is denominated in
	Amount *Monetary `json:"amount,omitempty"`
	// Where a send stage puts the funds
	Destination *StageSendDestination `json:"destination,omitempty"`
	// Where a send stage takes the funds from
	Source *StageSendSource `json:"source,omitempty"`
	// Metadata to attach to the resulting transaction
	Metadata map[string]string `json:"metadata,omitempty"`
	// The transaction time to record on the resulting transaction. See [bi-temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

func (s StageSend) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StageSend) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *StageSend) GetAmount() *Monetary {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *StageSend) GetDestination() *StageSendDestination {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *StageSend) GetSource() *StageSendSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *StageSend) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *StageSend) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}
