// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// StageSendSourceWallet - Take the funds from a wallet
type StageSendSourceWallet struct {
	// Identifier of the wallet to take funds from
	ID string `json:"id"`
	// Name of the balance within the wallet. Defaults to the main balance when omitted
	Balance *string `json:"balance,omitempty"`
}

func (o *StageSendSourceWallet) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *StageSendSourceWallet) GetBalance() *string {
	if o == nil {
		return nil
	}
	return o.Balance
}
