// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/flows/pkg/client/internal/utils"
)

// Type of transfer initiation:
// - TRANSFER: Internal to internal account transfer
// - PAYOUT: Internal to external account payout
type Type string

const (
	TypeTransfer Type = "TRANSFER"
	TypePayout   Type = "PAYOUT"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TRANSFER":
		fallthrough
	case "PAYOUT":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type StageSendDestinationPayment struct {
	// Payment service provider name (e.g., stripe, wise, mangopay).
	// Validated by the Payments service based on installed connectors.
	//
	Psp string `json:"psp"`
	// Type of transfer initiation:
	// - TRANSFER: Internal to internal account transfer
	// - PAYOUT: Internal to external account payout
	//
	Type *Type `default:"TRANSFER" json:"type"`
	// Formance Payments account ID for the source (internal PSP account).
	// If not specified, the Payments service may use a default account for the connector.
	//
	SourceAccount *string `json:"sourceAccount,omitempty"`
}

func (s StageSendDestinationPayment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StageSendDestinationPayment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *StageSendDestinationPayment) GetPsp() string {
	if o == nil {
		return ""
	}
	return o.Psp
}

func (o *StageSendDestinationPayment) GetType() *Type {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *StageSendDestinationPayment) GetSourceAccount() *string {
	if o == nil {
		return nil
	}
	return o.SourceAccount
}
