// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type StageDelay struct {
	Until    *time.Time `json:"until,omitempty"`
	Duration *string    `json:"duration,omitempty"`
}

func (s StageDelay) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StageDelay) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *StageDelay) GetUntil() *time.Time {
	if o == nil {
		return nil
	}
	return o.Until
}

func (o *StageDelay) GetDuration() *string {
	if o == nil {
		return nil
	}
	return o.Duration
}
