// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StageSendDestination struct {
	Wallet  *StageSendDestinationWallet  `json:"wallet,omitempty"`
	Account *StageSendDestinationAccount `json:"account,omitempty"`
	Payment *StageSendDestinationPayment `json:"payment,omitempty"`
}

func (o *StageSendDestination) GetWallet() *StageSendDestinationWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}

func (o *StageSendDestination) GetAccount() *StageSendDestinationAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *StageSendDestination) GetPayment() *StageSendDestinationPayment {
	if o == nil {
		return nil
	}
	return o.Payment
}
