// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type TriggerOccurrence struct {
	Date               time.Time         `json:"date"`
	WorkflowInstanceID *string           `json:"workflowInstanceID,omitempty"`
	WorkflowInstance   *WorkflowInstance `json:"workflowInstance,omitempty"`
	TriggerID          string            `json:"triggerID"`
	Event              map[string]any    `json:"event"`
	Error              *string           `json:"error,omitempty"`
}

func (t TriggerOccurrence) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerOccurrence) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TriggerOccurrence) GetDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Date
}

func (o *TriggerOccurrence) GetWorkflowInstanceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkflowInstanceID
}

func (o *TriggerOccurrence) GetWorkflowInstance() *WorkflowInstance {
	if o == nil {
		return nil
	}
	return o.WorkflowInstance
}

func (o *TriggerOccurrence) GetTriggerID() string {
	if o == nil {
		return ""
	}
	return o.TriggerID
}

func (o *TriggerOccurrence) GetEvent() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Event
}

func (o *TriggerOccurrence) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}
