// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// Trigger - A rule that starts a workflow when a matching event arrives
type Trigger struct {
	// Type of event that fires this trigger
	Event string `json:"event"`
	// Identifier of the workflow to run when the trigger fires
	WorkflowID string `json:"workflowID"`
	// Version of the trigger definition
	Version *string `json:"version,omitempty"`
	// Expression evaluated against the event. The workflow runs only when it matches
	Filter *string `json:"filter,omitempty"`
	// Expressions evaluated against the event to build the workflow's input variables
	Vars map[string]any `json:"vars,omitempty"`
	// Human-readable name for the trigger
	Name      *string   `json:"name,omitempty"`
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
}

func (t Trigger) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Trigger) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Trigger) GetEvent() string {
	if o == nil {
		return ""
	}
	return o.Event
}

func (o *Trigger) GetWorkflowID() string {
	if o == nil {
		return ""
	}
	return o.WorkflowID
}

func (o *Trigger) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *Trigger) GetFilter() *string {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *Trigger) GetVars() map[string]any {
	if o == nil {
		return nil
	}
	return o.Vars
}

func (o *Trigger) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Trigger) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Trigger) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}
