// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type TriggerOccurrence struct {
	// When the trigger fired
	Date time.Time `json:"date"`
	// Identifier of the run the trigger started, absent when it started none
	WorkflowInstanceID *string `json:"workflowInstanceID,omitempty"`
	// One run of a workflow, tracking its per-stage progress
	WorkflowInstance *WorkflowInstance `json:"workflowInstance,omitempty"`
	// Identifier of the trigger that fired
	TriggerID string `json:"triggerID"`
	// The event that fired the trigger
	Event map[string]any `json:"event"`
	// Why the trigger failed to start a run, absent when it succeeded
	Error *string `json:"error,omitempty"`
}

func (t TriggerOccurrence) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerOccurrence) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TriggerOccurrence) GetDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Date
}

func (o *TriggerOccurrence) GetWorkflowInstanceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkflowInstanceID
}

func (o *TriggerOccurrence) GetWorkflowInstance() *WorkflowInstance {
	if o == nil {
		return nil
	}
	return o.WorkflowInstance
}

func (o *TriggerOccurrence) GetTriggerID() string {
	if o == nil {
		return ""
	}
	return o.TriggerID
}

func (o *TriggerOccurrence) GetEvent() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Event
}

func (o *TriggerOccurrence) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}
