// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TriggerData struct {
	// Type of event that fires this trigger
	Event string `json:"event"`
	// Identifier of the workflow to run when the trigger fires
	WorkflowID string `json:"workflowID"`
	// Version of the trigger definition
	Version *string `json:"version,omitempty"`
	// Expression evaluated against the event. The workflow runs only when it matches
	Filter *string `json:"filter,omitempty"`
	// Expressions evaluated against the event to build the workflow's input variables
	Vars map[string]any `json:"vars,omitempty"`
	// Human-readable name for the trigger
	Name *string `json:"name,omitempty"`
}

func (o *TriggerData) GetEvent() string {
	if o == nil {
		return ""
	}
	return o.Event
}

func (o *TriggerData) GetWorkflowID() string {
	if o == nil {
		return ""
	}
	return o.WorkflowID
}

func (o *TriggerData) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *TriggerData) GetFilter() *string {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *TriggerData) GetVars() map[string]any {
	if o == nil {
		return nil
	}
	return o.Vars
}

func (o *TriggerData) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
