// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateAccount struct {
	ID       string            `json:"id"`
	Metadata map[string]string `json:"metadata"`
	Ledger   string            `json:"ledger"`
}

func (o *UpdateAccount) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateAccount) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *UpdateAccount) GetLedger() string {
	if o == nil {
		return ""
	}
	return o.Ledger
}
