// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Update struct {
	// Metadata to set on a ledger account
	Account *UpdateAccount `json:"account,omitempty"`
}

func (o *Update) GetAccount() *UpdateAccount {
	if o == nil {
		return nil
	}
	return o.Account
}
