// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2ActivityListWallets - Arguments for the activity that lists wallets
type V2ActivityListWallets struct {
	// Restrict the listing to wallets with this name
	Name *string `json:"name,omitempty"`
}

func (o *V2ActivityListWallets) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
