// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2ActivityDebitWallet struct {
	ID   *string               `json:"id,omitempty"`
	Data *V2DebitWalletRequest `json:"data,omitempty"`
}

func (o *V2ActivityDebitWallet) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *V2ActivityDebitWallet) GetData() *V2DebitWalletRequest {
	if o == nil {
		return nil
	}
	return o.Data
}
