// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2ActivityGetPayment - Arguments for the activity that reads a payment
type V2ActivityGetPayment struct {
	// Identifier of the payment to read
	ID string `json:"id"`
}

func (o *V2ActivityGetPayment) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
