// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2ActivityCreditWallet - Arguments for the activity that credits a wallet
type V2ActivityCreditWallet struct {
	// Identifier of the wallet to credit
	ID *string `json:"id,omitempty"`
	// A credit to apply to a wallet
	Data *V2CreditWalletRequest `json:"data,omitempty"`
}

func (o *V2ActivityCreditWallet) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *V2ActivityCreditWallet) GetData() *V2CreditWalletRequest {
	if o == nil {
		return nil
	}
	return o.Data
}
