// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2ActivityDebitWallet - Arguments for the activity that debits a wallet
type V2ActivityDebitWallet struct {
	// Identifier of the wallet to debit
	ID *string `json:"id,omitempty"`
	// A debit to apply to a wallet
	Data *V2DebitWalletRequest `json:"data,omitempty"`
}

func (o *V2ActivityDebitWallet) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *V2ActivityDebitWallet) GetData() *V2DebitWalletRequest {
	if o == nil {
		return nil
	}
	return o.Data
}
