// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2AccountResponse struct {
	// An account in the ledger, identified by its address
	Data V2Account `json:"data"`
}

func (o *V2AccountResponse) GetData() V2Account {
	if o == nil {
		return V2Account{}
	}
	return o.Data
}
