// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2ActivityCreateTransaction - Arguments for the activity that writes a transaction to a ledger
type V2ActivityCreateTransaction struct {
	// Name of the ledger to write the transaction to
	Ledger *string `json:"ledger,omitempty"`
	// A transaction to write to a ledger
	Data *V2PostTransaction `json:"data,omitempty"`
}

func (o *V2ActivityCreateTransaction) GetLedger() *string {
	if o == nil {
		return nil
	}
	return o.Ledger
}

func (o *V2ActivityCreateTransaction) GetData() *V2PostTransaction {
	if o == nil {
		return nil
	}
	return o.Data
}
