// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2ActivityGetWallet - Arguments for the activity that reads a wallet
type V2ActivityGetWallet struct {
	// Identifier of the wallet to read
	ID string `json:"id"`
}

func (o *V2ActivityGetWallet) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
