// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/flows/pkg/client/internal/utils"
	"math/big"
)

// V2ActivityCreateTransferInitiationType - Type of transfer initiation:
// - TRANSFER: Internal to internal account transfer
// - PAYOUT: Internal to external account payout
type V2ActivityCreateTransferInitiationType string

const (
	V2ActivityCreateTransferInitiationTypeTransfer V2ActivityCreateTransferInitiationType = "TRANSFER"
	V2ActivityCreateTransferInitiationTypePayout   V2ActivityCreateTransferInitiationType = "PAYOUT"
)

func (e V2ActivityCreateTransferInitiationType) ToPointer() *V2ActivityCreateTransferInitiationType {
	return &e
}
func (e *V2ActivityCreateTransferInitiationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TRANSFER":
		fallthrough
	case "PAYOUT":
		*e = V2ActivityCreateTransferInitiationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2ActivityCreateTransferInitiationType: %v", v)
	}
}

// V2ActivityCreateTransferInitiationMetadata - A set of key/value pairs that you can attach to a transfer object. It can be useful for storing additional information about the transfer in a structured format.
type V2ActivityCreateTransferInitiationMetadata struct {
}

type V2ActivityCreateTransferInitiation struct {
	ConnectorID *string `json:"connectorID,omitempty"`
	// Payment service provider name (e.g., stripe, wise, mangopay).
	// Validated by the Payments service based on installed connectors.
	//
	Provider *string  `json:"provider,omitempty"`
	Amount   *big.Int `json:"amount,omitempty"`
	Asset    *string  `json:"asset,omitempty"`
	// Destination account ID
	Destination *string `json:"destination,omitempty"`
	// Source account ID (required for TRANSFER type)
	Source *string `json:"source,omitempty"`
	// Type of transfer initiation:
	// - TRANSFER: Internal to internal account transfer
	// - PAYOUT: Internal to external account payout
	//
	Type *V2ActivityCreateTransferInitiationType `default:"TRANSFER" json:"type"`
	// Description for the transfer initiation
	Description       *string `json:"description,omitempty"`
	WaitingValidation *bool   `default:"false" json:"waitingValidation"`
	// A set of key/value pairs that you can attach to a transfer object. It can be useful for storing additional information about the transfer in a structured format.
	//
	Metadata *V2ActivityCreateTransferInitiationMetadata `json:"metadata,omitempty"`
}

func (v V2ActivityCreateTransferInitiation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2ActivityCreateTransferInitiation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2ActivityCreateTransferInitiation) GetConnectorID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectorID
}

func (o *V2ActivityCreateTransferInitiation) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *V2ActivityCreateTransferInitiation) GetAmount() *big.Int {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *V2ActivityCreateTransferInitiation) GetAsset() *string {
	if o == nil {
		return nil
	}
	return o.Asset
}

func (o *V2ActivityCreateTransferInitiation) GetDestination() *string {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *V2ActivityCreateTransferInitiation) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *V2ActivityCreateTransferInitiation) GetType() *V2ActivityCreateTransferInitiationType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *V2ActivityCreateTransferInitiation) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *V2ActivityCreateTransferInitiation) GetWaitingValidation() *bool {
	if o == nil {
		return nil
	}
	return o.WaitingValidation
}

func (o *V2ActivityCreateTransferInitiation) GetMetadata() *V2ActivityCreateTransferInitiationMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}
