// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2ActivityPause - Current pause of an activity in an active stage, read from Temporal on instance detail requests
type V2ActivityPause struct {
	// Stable activity identifier within the owning workflow execution
	ActivityID string `json:"activityID"`
	// Run identifier of the described stage workflow execution
	TemporalRunID string `json:"temporalRunID"`
	// Activity type name
	Name string `json:"name"`
	// Current attempt counter reported by Temporal
	Attempt int64 `json:"attempt"`
	// Message of the most recent failed attempt, when available
	LastFailure *string `json:"lastFailure,omitempty"`
	// Application failure type of the most recent failed attempt, when available
	LastFailureType *string `json:"lastFailureType,omitempty"`
	// Reason recorded by Temporal for this pause, when available
	Reason *string `json:"reason,omitempty"`
	// Attempt limit decoded from an ACTIVITY_ATTEMPT_LIMIT:<limit> pause reason, when valid
	MaxAttempts *int64 `json:"maxAttempts,omitempty"`
}

func (o *V2ActivityPause) GetActivityID() string {
	if o == nil {
		return ""
	}
	return o.ActivityID
}

func (o *V2ActivityPause) GetTemporalRunID() string {
	if o == nil {
		return ""
	}
	return o.TemporalRunID
}

func (o *V2ActivityPause) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V2ActivityPause) GetAttempt() int64 {
	if o == nil {
		return 0
	}
	return o.Attempt
}

func (o *V2ActivityPause) GetLastFailure() *string {
	if o == nil {
		return nil
	}
	return o.LastFailure
}

func (o *V2ActivityPause) GetLastFailureType() *string {
	if o == nil {
		return nil
	}
	return o.LastFailureType
}

func (o *V2ActivityPause) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}

func (o *V2ActivityPause) GetMaxAttempts() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxAttempts
}
