// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2ActivityCreditWallet struct {
	ID   *string                `json:"id,omitempty"`
	Data *V2CreditWalletRequest `json:"data,omitempty"`
}

func (o *V2ActivityCreditWallet) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *V2ActivityCreditWallet) GetData() *V2CreditWalletRequest {
	if o == nil {
		return nil
	}
	return o.Data
}
