// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// V2CreditWalletRequest - A credit to apply to a wallet
type V2CreditWalletRequest struct {
	// An amount together with the asset it is denominated in
	Amount V2Monetary `json:"amount"`
	// Metadata associated with the wallet.
	Metadata map[string]string `json:"metadata"`
	// Optional caller-supplied identifier used to deduplicate the credit
	Reference *string `json:"reference,omitempty"`
	// Where the funds come from
	Sources []V2Subject `json:"sources"`
	// The balance to credit
	Balance *string `json:"balance,omitempty"`
	// The transaction time to record on the resulting transaction. See [bi-temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

func (v V2CreditWalletRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2CreditWalletRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2CreditWalletRequest) GetAmount() V2Monetary {
	if o == nil {
		return V2Monetary{}
	}
	return o.Amount
}

func (o *V2CreditWalletRequest) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *V2CreditWalletRequest) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *V2CreditWalletRequest) GetSources() []V2Subject {
	if o == nil {
		return []V2Subject{}
	}
	return o.Sources
}

func (o *V2CreditWalletRequest) GetBalance() *string {
	if o == nil {
		return nil
	}
	return o.Balance
}

func (o *V2CreditWalletRequest) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}
