// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"math/big"
	"openapi/internal/utils"
)

// V2CreateTransferInitiationRequestType - Type of transfer initiation:
// - TRANSFER: Internal to internal account transfer
// - PAYOUT: Internal to external account payout
type V2CreateTransferInitiationRequestType string

const (
	V2CreateTransferInitiationRequestTypeTransfer V2CreateTransferInitiationRequestType = "TRANSFER"
	V2CreateTransferInitiationRequestTypePayout   V2CreateTransferInitiationRequestType = "PAYOUT"
)

func (e V2CreateTransferInitiationRequestType) ToPointer() *V2CreateTransferInitiationRequestType {
	return &e
}
func (e *V2CreateTransferInitiationRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TRANSFER":
		fallthrough
	case "PAYOUT":
		*e = V2CreateTransferInitiationRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2CreateTransferInitiationRequestType: %v", v)
	}
}

// V2CreateTransferInitiationRequestMetadata - A set of key/value pairs that you can attach to a transfer object. It can be useful for storing additional information about the transfer in a structured format.
type V2CreateTransferInitiationRequestMetadata struct {
}

type V2CreateTransferInitiationRequest struct {
	// Identifier of the connector to transfer through
	ConnectorID *string `json:"connectorID,omitempty"`
	// Payment service provider name (e.g., stripe, wise, mangopay).
	// Validated by the Payments service based on installed connectors.
	//
	Provider *string `json:"provider,omitempty"`
	// Amount to transfer, in the asset's smallest unit
	Amount *big.Int `json:"amount,omitempty"`
	// Asset the transfer is denominated in
	Asset *string `json:"asset,omitempty"`
	// Destination account ID
	Destination *string `json:"destination,omitempty"`
	// Source account ID (required for TRANSFER type)
	Source *string `json:"source,omitempty"`
	// Type of transfer initiation:
	// - TRANSFER: Internal to internal account transfer
	// - PAYOUT: Internal to external account payout
	//
	Type *V2CreateTransferInitiationRequestType `default:"TRANSFER" json:"type"`
	// Description for the transfer initiation
	Description *string `json:"description,omitempty"`
	// When true, the transfer is created but held until it is validated
	WaitingValidation *bool `default:"false" json:"waitingValidation"`
	// A set of key/value pairs that you can attach to a transfer object. It can be useful for storing additional information about the transfer in a structured format.
	//
	Metadata *V2CreateTransferInitiationRequestMetadata `json:"metadata,omitempty"`
}

func (v V2CreateTransferInitiationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2CreateTransferInitiationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2CreateTransferInitiationRequest) GetConnectorID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectorID
}

func (o *V2CreateTransferInitiationRequest) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *V2CreateTransferInitiationRequest) GetAmount() *big.Int {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *V2CreateTransferInitiationRequest) GetAsset() *string {
	if o == nil {
		return nil
	}
	return o.Asset
}

func (o *V2CreateTransferInitiationRequest) GetDestination() *string {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *V2CreateTransferInitiationRequest) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *V2CreateTransferInitiationRequest) GetType() *V2CreateTransferInitiationRequestType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *V2CreateTransferInitiationRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *V2CreateTransferInitiationRequest) GetWaitingValidation() *bool {
	if o == nil {
		return nil
	}
	return o.WaitingValidation
}

func (o *V2CreateTransferInitiationRequest) GetMetadata() *V2CreateTransferInitiationRequestMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}
