// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2CreateTriggerResponse struct {
	// A rule that starts a workflow when a matching event arrives
	Data V2Trigger `json:"data"`
}

func (o *V2CreateTriggerResponse) GetData() V2Trigger {
	if o == nil {
		return V2Trigger{}
	}
	return o.Data
}
