// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2CreateWorkflowRequest - The stages a workflow runs, in order
type V2CreateWorkflowRequest struct {
	// Human-readable name for the workflow
	Name *string `json:"name,omitempty"`
	// The stages executed in order when the workflow runs
	Stages []map[string]any `json:"stages"`
}

func (o *V2CreateWorkflowRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *V2CreateWorkflowRequest) GetStages() []map[string]any {
	if o == nil {
		return []map[string]any{}
	}
	return o.Stages
}
