// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2DebitWalletResponse struct {
	// Funds locked by a pending wallet debit, later either confirmed or voided
	Data V2Hold `json:"data"`
}

func (o *V2DebitWalletResponse) GetData() V2Hold {
	if o == nil {
		return V2Hold{}
	}
	return o.Data
}
