// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2GetWorkflowResponse struct {
	// A workflow definition and the stages it runs
	Data V2Workflow `json:"data"`
}

func (o *V2GetWorkflowResponse) GetData() V2Workflow {
	if o == nil {
		return V2Workflow{}
	}
	return o.Data
}
