// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2GetWalletResponse struct {
	// A wallet together with the funds it currently holds
	Data V2WalletWithBalances `json:"data"`
}

func (o *V2GetWalletResponse) GetData() V2WalletWithBalances {
	if o == nil {
		return V2WalletWithBalances{}
	}
	return o.Data
}
