// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2Hold - Funds locked by a pending wallet debit, later either confirmed or voided
type V2Hold struct {
	// The unique ID of the hold.
	ID string `json:"id"`
	// The ID of the wallet the hold is associated with.
	WalletID string `json:"walletID"`
	// Metadata associated with the hold.
	Metadata map[string]string `json:"metadata"`
	// Human-readable reason the funds were held
	Description string `json:"description"`
	// The counterparty of a wallet movement, either a ledger account or another wallet
	Destination *V2Subject `json:"destination,omitempty"`
}

func (o *V2Hold) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V2Hold) GetWalletID() string {
	if o == nil {
		return ""
	}
	return o.WalletID
}

func (o *V2Hold) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *V2Hold) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *V2Hold) GetDestination() *V2Subject {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *V2Hold) GetDestinationAccount() *V2LedgerAccountSubject {
	if v := o.GetDestination(); v != nil {
		return v.V2LedgerAccountSubject
	}
	return nil
}

func (o *V2Hold) GetDestinationWallet() *V2WalletSubject {
	if v := o.GetDestination(); v != nil {
		return v.V2WalletSubject
	}
	return nil
}
