// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2LedgerAccountSubject struct {
	Type       string `json:"type"`
	Identifier string `json:"identifier"`
}

func (o *V2LedgerAccountSubject) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *V2LedgerAccountSubject) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}
