// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2ListTriggersOccurrencesResponseCursor struct {
	PageSize int64                 `json:"pageSize"`
	HasMore  bool                  `json:"hasMore"`
	Previous *string               `json:"previous,omitempty"`
	Next     *string               `json:"next,omitempty"`
	Data     []V2TriggerOccurrence `json:"data"`
}

func (o *V2ListTriggersOccurrencesResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V2ListTriggersOccurrencesResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V2ListTriggersOccurrencesResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V2ListTriggersOccurrencesResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V2ListTriggersOccurrencesResponseCursor) GetData() []V2TriggerOccurrence {
	if o == nil {
		return []V2TriggerOccurrence{}
	}
	return o.Data
}

type V2ListTriggersOccurrencesResponse struct {
	Cursor V2ListTriggersOccurrencesResponseCursor `json:"cursor"`
}

func (o *V2ListTriggersOccurrencesResponse) GetCursor() V2ListTriggersOccurrencesResponseCursor {
	if o == nil {
		return V2ListTriggersOccurrencesResponseCursor{}
	}
	return o.Cursor
}
