// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2ListRunsResponseCursor struct {
	PageSize int64                `json:"pageSize"`
	HasMore  bool                 `json:"hasMore"`
	Previous *string              `json:"previous,omitempty"`
	Next     *string              `json:"next,omitempty"`
	Data     []V2WorkflowInstance `json:"data"`
}

func (o *V2ListRunsResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V2ListRunsResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V2ListRunsResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V2ListRunsResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V2ListRunsResponseCursor) GetData() []V2WorkflowInstance {
	if o == nil {
		return []V2WorkflowInstance{}
	}
	return o.Data
}

type V2ListRunsResponse struct {
	Cursor V2ListRunsResponseCursor `json:"cursor"`
}

func (o *V2ListRunsResponse) GetCursor() V2ListRunsResponseCursor {
	if o == nil {
		return V2ListRunsResponseCursor{}
	}
	return o.Cursor
}
