// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2ListWalletsResponseCursor - Paginated cursor wrapping the list of wallets
type V2ListWalletsResponseCursor struct {
	// Number of items requested per page
	PageSize int64 `json:"pageSize"`
	// Whether further pages are available
	HasMore *bool `json:"hasMore,omitempty"`
	// Cursor for the previous page, absent on the first page
	Previous *string `json:"previous,omitempty"`
	// Cursor for the next page, absent on the last page
	Next *string    `json:"next,omitempty"`
	Data []V2Wallet `json:"data"`
}

func (o *V2ListWalletsResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V2ListWalletsResponseCursor) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}

func (o *V2ListWalletsResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V2ListWalletsResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V2ListWalletsResponseCursor) GetData() []V2Wallet {
	if o == nil {
		return []V2Wallet{}
	}
	return o.Data
}

// V2ListWalletsResponse - A page of wallets
type V2ListWalletsResponse struct {
	// Paginated cursor wrapping the list of wallets
	Cursor V2ListWalletsResponseCursor `json:"cursor"`
}

func (o *V2ListWalletsResponse) GetCursor() V2ListWalletsResponseCursor {
	if o == nil {
		return V2ListWalletsResponseCursor{}
	}
	return o.Cursor
}
