// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"math/big"
	"openapi/internal/utils"
)

type V2Monetary struct {
	// The asset of the monetary value.
	Asset string `json:"asset"`
	// The amount of the monetary value.
	Amount *big.Int `json:"amount"`
}

func (v V2Monetary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2Monetary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2Monetary) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *V2Monetary) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}
