// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2PaymentResponse struct {
	// A payment observed or initiated through a connector
	Data V2Payment `json:"data"`
}

func (o *V2PaymentResponse) GetData() V2Payment {
	if o == nil {
		return V2Payment{}
	}
	return o.Data
}
