// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"math/big"
	"openapi/internal/utils"
	"time"
)

// V2PaymentAdjustmentRaw - The provider's original payload for this adjustment
type V2PaymentAdjustmentRaw struct {
}

type V2PaymentAdjustment struct {
	// Where a payment stands in its lifecycle
	Status V2PaymentStatus `json:"status"`
	// Amount carried by this adjustment
	Amount *big.Int `json:"amount"`
	// When the adjustment was recorded
	Date time.Time `json:"date"`
	// The provider's original payload for this adjustment
	Raw V2PaymentAdjustmentRaw `json:"raw"`
	// Whether amount replaces the payment's amount rather than adding to it
	Absolute bool `json:"absolute"`
}

func (v V2PaymentAdjustment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2PaymentAdjustment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2PaymentAdjustment) GetStatus() V2PaymentStatus {
	if o == nil {
		return V2PaymentStatus("")
	}
	return o.Status
}

func (o *V2PaymentAdjustment) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *V2PaymentAdjustment) GetDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Date
}

func (o *V2PaymentAdjustment) GetRaw() V2PaymentAdjustmentRaw {
	if o == nil {
		return V2PaymentAdjustmentRaw{}
	}
	return o.Raw
}

func (o *V2PaymentAdjustment) GetAbsolute() bool {
	if o == nil {
		return false
	}
	return o.Absolute
}
