// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// V2PostTransactionScript - A Numscript program executed to produce the postings. Mutually exclusive with postings
type V2PostTransactionScript struct {
	Plain string         `json:"plain"`
	Vars  map[string]any `json:"vars,omitempty"`
}

func (o *V2PostTransactionScript) GetPlain() string {
	if o == nil {
		return ""
	}
	return o.Plain
}

func (o *V2PostTransactionScript) GetVars() map[string]any {
	if o == nil {
		return nil
	}
	return o.Vars
}

// V2PostTransaction - A transaction to write to a ledger
type V2PostTransaction struct {
	// The transaction time to record, letting you backdate or postdate the transaction. See [bi-temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Fund movements to apply. Mutually exclusive with script
	Postings []V2Posting `json:"postings,omitempty"`
	// A Numscript program executed to produce the postings. Mutually exclusive with postings
	Script *V2PostTransactionScript `json:"script,omitempty"`
	// Optional caller-supplied identifier, unique within the ledger, used to deduplicate transactions
	Reference *string `json:"reference,omitempty"`
	// Arbitrary key/value pairs attached to the resource
	Metadata map[string]string `json:"metadata"`
}

func (v V2PostTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2PostTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2PostTransaction) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}

func (o *V2PostTransaction) GetPostings() []V2Posting {
	if o == nil {
		return nil
	}
	return o.Postings
}

func (o *V2PostTransaction) GetScript() *V2PostTransactionScript {
	if o == nil {
		return nil
	}
	return o.Script
}

func (o *V2PostTransaction) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *V2PostTransaction) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}
