// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2ServerInfo struct {
	// Version of the orchestration service
	Version string `json:"version"`
}

func (o *V2ServerInfo) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}
