// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2StageSendDestinationWallet struct {
	ID      string  `json:"id"`
	Balance *string `json:"balance,omitempty"`
}

func (o *V2StageSendDestinationWallet) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V2StageSendDestinationWallet) GetBalance() *string {
	if o == nil {
		return nil
	}
	return o.Balance
}
