// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type V2StageStatus struct {
	// Zero-based position of the stage within the workflow
	Stage float64 `json:"stage"`
	// Identifier of the workflow instance this stage belongs to
	InstanceID string `json:"instanceID"`
	// When the stage started
	StartedAt time.Time `json:"startedAt"`
	// When the stage finished, absent while it is still running
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`
	// Why the stage failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
}

func (v V2StageStatus) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2StageStatus) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2StageStatus) GetStage() float64 {
	if o == nil {
		return 0.0
	}
	return o.Stage
}

func (o *V2StageStatus) GetInstanceID() string {
	if o == nil {
		return ""
	}
	return o.InstanceID
}

func (o *V2StageStatus) GetStartedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartedAt
}

func (o *V2StageStatus) GetTerminatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.TerminatedAt
}

func (o *V2StageStatus) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}
