// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2StageSendSource struct {
	Wallet  *V2StageSendSourceWallet  `json:"wallet,omitempty"`
	Account *V2StageSendSourceAccount `json:"account,omitempty"`
	Payment *V2StageSendSourcePayment `json:"payment,omitempty"`
}

func (o *V2StageSendSource) GetWallet() *V2StageSendSourceWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}

func (o *V2StageSendSource) GetAccount() *V2StageSendSourceAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *V2StageSendSource) GetPayment() *V2StageSendSourcePayment {
	if o == nil {
		return nil
	}
	return o.Payment
}
