// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2StageSendSource - Where a send stage takes the funds from
type V2StageSendSource struct {
	// Take the funds from a wallet
	Wallet *V2StageSendSourceWallet `json:"wallet,omitempty"`
	// Take the funds from a ledger account
	Account *V2StageSendSourceAccount `json:"account,omitempty"`
	// Take the funds from a payment
	Payment *V2StageSendSourcePayment `json:"payment,omitempty"`
}

func (o *V2StageSendSource) GetWallet() *V2StageSendSourceWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}

func (o *V2StageSendSource) GetAccount() *V2StageSendSourceAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *V2StageSendSource) GetPayment() *V2StageSendSourcePayment {
	if o == nil {
		return nil
	}
	return o.Payment
}
