// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type V2StageSend struct {
	// An amount together with the asset it is denominated in
	Amount *V2Monetary `json:"amount,omitempty"`
	// Where a send stage puts the funds
	Destination *V2StageSendDestination `json:"destination,omitempty"`
	// Where a send stage takes the funds from
	Source *V2StageSendSource `json:"source,omitempty"`
	// Metadata to attach to the resulting transaction
	Metadata map[string]string `json:"metadata,omitempty"`
	// The transaction time to record on the resulting transaction. See [bi-temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

func (v V2StageSend) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2StageSend) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *V2StageSend) GetAmount() *V2Monetary {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *V2StageSend) GetDestination() *V2StageSendDestination {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *V2StageSend) GetSource() *V2StageSendSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *V2StageSend) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *V2StageSend) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}
