// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2StageSendDestination - Where a send stage puts the funds
type V2StageSendDestination struct {
	// Send the funds to a wallet
	Wallet *V2StageSendSourceWallet `json:"wallet,omitempty"`
	// Send the funds to a ledger account
	Account *V2StageSendSourceAccount `json:"account,omitempty"`
	// Send the funds to a payment
	Payment *V2StageSendDestinationPayment `json:"payment,omitempty"`
}

func (o *V2StageSendDestination) GetWallet() *V2StageSendSourceWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}

func (o *V2StageSendDestination) GetAccount() *V2StageSendSourceAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *V2StageSendDestination) GetPayment() *V2StageSendDestinationPayment {
	if o == nil {
		return nil
	}
	return o.Payment
}
