// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2StageWaitEvent struct {
	// Type of event the workflow waits for before continuing
	Event string `json:"event"`
}

func (o *V2StageWaitEvent) GetEvent() string {
	if o == nil {
		return ""
	}
	return o.Event
}
