// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"math/big"
	"openapi/internal/utils"
)

// V2StripeTransferRequestMetadata - A set of key/value pairs that you can attach to a transfer object.
// It can be useful for storing additional information about the transfer in a structured format.
type V2StripeTransferRequestMetadata struct {
}

type V2StripeTransferRequest struct {
	// Identifier of the Stripe connector to transfer through
	ConnectorID *string `json:"connectorID,omitempty"`
	// Amount to transfer, in the asset's smallest unit
	Amount *big.Int `json:"amount,omitempty"`
	// Asset the transfer is denominated in
	Asset *string `json:"asset,omitempty"`
	// Stripe connected account receiving the transfer
	Destination *string `json:"destination,omitempty"`
	// When true, the transfer is created but held until it is validated
	WaitingValidation *bool `default:"false" json:"waitingValidation"`
	// A set of key/value pairs that you can attach to a transfer object.
	// It can be useful for storing additional information about the transfer in a structured format.
	//
	Metadata *V2StripeTransferRequestMetadata `json:"metadata,omitempty"`
}

func (v V2StripeTransferRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2StripeTransferRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2StripeTransferRequest) GetConnectorID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectorID
}

func (o *V2StripeTransferRequest) GetAmount() *big.Int {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *V2StripeTransferRequest) GetAsset() *string {
	if o == nil {
		return nil
	}
	return o.Asset
}

func (o *V2StripeTransferRequest) GetDestination() *string {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *V2StripeTransferRequest) GetWaitingValidation() *bool {
	if o == nil {
		return nil
	}
	return o.WaitingValidation
}

func (o *V2StripeTransferRequest) GetMetadata() *V2StripeTransferRequestMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}
