// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"math/big"
	"openapi/internal/utils"
	"time"
)

type V2Transaction struct {
	Timestamp time.Time         `json:"timestamp"`
	Postings  []V2Posting       `json:"postings"`
	Reference *string           `json:"reference,omitempty"`
	Metadata  map[string]string `json:"metadata"`
	Txid      *big.Int          `json:"txid"`
}

func (v V2Transaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2Transaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2Transaction) GetTimestamp() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Timestamp
}

func (o *V2Transaction) GetPostings() []V2Posting {
	if o == nil {
		return []V2Posting{}
	}
	return o.Postings
}

func (o *V2Transaction) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *V2Transaction) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *V2Transaction) GetTxid() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Txid
}
