// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Filter struct {
	Match *bool   `json:"match,omitempty"`
	Error *string `json:"error,omitempty"`
}

func (o *Filter) GetMatch() *bool {
	if o == nil {
		return nil
	}
	return o.Match
}

func (o *Filter) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

type Variables struct {
	Value *string `json:"value,omitempty"`
	Error *string `json:"error,omitempty"`
}

func (o *Variables) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *Variables) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

type V2TriggerTest struct {
	Filter    *Filter              `json:"filter,omitempty"`
	Variables map[string]Variables `json:"variables,omitempty"`
}

func (o *V2TriggerTest) GetFilter() *Filter {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *V2TriggerTest) GetVariables() map[string]Variables {
	if o == nil {
		return nil
	}
	return o.Variables
}
