// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Filter - How the trigger's filter evaluated against the sample event
type Filter struct {
	Match *bool   `json:"match,omitempty"`
	Error *string `json:"error,omitempty"`
}

func (o *Filter) GetMatch() *bool {
	if o == nil {
		return nil
	}
	return o.Match
}

func (o *Filter) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

type Variables struct {
	Value *string `json:"value,omitempty"`
	Error *string `json:"error,omitempty"`
}

func (o *Variables) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *Variables) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

// V2TriggerTest - Result of evaluating a trigger against a sample event, without running the workflow
type V2TriggerTest struct {
	// How the trigger's filter evaluated against the sample event
	Filter *Filter `json:"filter,omitempty"`
	// The variables the trigger would build from the sample event
	Variables map[string]Variables `json:"variables,omitempty"`
}

func (o *V2TriggerTest) GetFilter() *Filter {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *V2TriggerTest) GetVariables() map[string]Variables {
	if o == nil {
		return nil
	}
	return o.Variables
}
