// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type V2TriggerOccurrence struct {
	// When the trigger fired
	Date time.Time `json:"date"`
	// Identifier of the run the trigger started, absent when it started none
	WorkflowInstanceID *string `json:"workflowInstanceID,omitempty"`
	// One run of a workflow, tracking its per-stage progress
	WorkflowInstance *V2WorkflowInstance `json:"workflowInstance,omitempty"`
	// Identifier of the trigger that fired
	TriggerID string `json:"triggerID"`
	// Why the trigger failed to start a run, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// The event that fired the trigger
	Event map[string]any `json:"event"`
}

func (v V2TriggerOccurrence) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2TriggerOccurrence) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2TriggerOccurrence) GetDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Date
}

func (o *V2TriggerOccurrence) GetWorkflowInstanceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkflowInstanceID
}

func (o *V2TriggerOccurrence) GetWorkflowInstance() *V2WorkflowInstance {
	if o == nil {
		return nil
	}
	return o.WorkflowInstance
}

func (o *V2TriggerOccurrence) GetTriggerID() string {
	if o == nil {
		return ""
	}
	return o.TriggerID
}

func (o *V2TriggerOccurrence) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *V2TriggerOccurrence) GetEvent() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Event
}
