// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2Update struct {
	// Metadata to set on a ledger account
	Account *V2UpdateAccount `json:"account,omitempty"`
}

func (o *V2Update) GetAccount() *V2UpdateAccount {
	if o == nil {
		return nil
	}
	return o.Account
}
