// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2UpdateAccount - Metadata to set on a ledger account
type V2UpdateAccount struct {
	// Address of the ledger account to update
	ID string `json:"id"`
	// Metadata to set on the account
	Metadata map[string]string `json:"metadata"`
	// Name of the ledger holding the account
	Ledger string `json:"ledger"`
}

func (o *V2UpdateAccount) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V2UpdateAccount) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *V2UpdateAccount) GetLedger() string {
	if o == nil {
		return ""
	}
	return o.Ledger
}
