// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2WalletSubject struct {
	// Discriminator identifying this subject as a wallet
	Type string `json:"type"`
	// Identifier of the wallet
	Identifier string `json:"identifier"`
	// Name of the balance within the wallet. Defaults to the main balance when omitted
	Balance *string `json:"balance,omitempty"`
}

func (o *V2WalletSubject) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *V2WalletSubject) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *V2WalletSubject) GetBalance() *string {
	if o == nil {
		return nil
	}
	return o.Balance
}
