// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type V2WorkflowInstance struct {
	WorkflowID   string          `json:"workflowID"`
	ID           string          `json:"id"`
	CreatedAt    time.Time       `json:"createdAt"`
	UpdatedAt    time.Time       `json:"updatedAt"`
	Status       []V2StageStatus `json:"status,omitempty"`
	Terminated   bool            `json:"terminated"`
	TerminatedAt *time.Time      `json:"terminatedAt,omitempty"`
	Error        *string         `json:"error,omitempty"`
	Workflow     *V2Workflow     `json:"workflow,omitempty"`
}

func (v V2WorkflowInstance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2WorkflowInstance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2WorkflowInstance) GetWorkflowID() string {
	if o == nil {
		return ""
	}
	return o.WorkflowID
}

func (o *V2WorkflowInstance) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V2WorkflowInstance) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *V2WorkflowInstance) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *V2WorkflowInstance) GetStatus() []V2StageStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *V2WorkflowInstance) GetTerminated() bool {
	if o == nil {
		return false
	}
	return o.Terminated
}

func (o *V2WorkflowInstance) GetTerminatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.TerminatedAt
}

func (o *V2WorkflowInstance) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *V2WorkflowInstance) GetWorkflow() *V2Workflow {
	if o == nil {
		return nil
	}
	return o.Workflow
}
