// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2WorkflowInstanceHistoryStageOutput - Result an activity returned, keyed by activity name
type V2WorkflowInstanceHistoryStageOutput struct {
	// Result of the activity that reads a ledger account
	GetAccount *V2AccountResponse `json:"GetAccount,omitempty"`
	// Result of the activity that writes a transaction to a ledger
	CreateTransaction *V2CreateTransactionResponse `json:"CreateTransaction,omitempty"`
	// Result of the activity that reads a payment
	GetPayment *V2PaymentResponse `json:"GetPayment,omitempty"`
	// Result of the activity that debits a wallet
	DebitWallet *V2DebitWalletResponse `json:"DebitWallet,omitempty"`
	// Result of the activity that reads a wallet
	GetWallet *V2GetWalletResponse `json:"GetWallet,omitempty"`
	// A page of wallets
	ListWallets *V2ListWalletsResponse `json:"ListWallets,omitempty"`
}

func (o *V2WorkflowInstanceHistoryStageOutput) GetGetAccount() *V2AccountResponse {
	if o == nil {
		return nil
	}
	return o.GetAccount
}

func (o *V2WorkflowInstanceHistoryStageOutput) GetCreateTransaction() *V2CreateTransactionResponse {
	if o == nil {
		return nil
	}
	return o.CreateTransaction
}

func (o *V2WorkflowInstanceHistoryStageOutput) GetGetPayment() *V2PaymentResponse {
	if o == nil {
		return nil
	}
	return o.GetPayment
}

func (o *V2WorkflowInstanceHistoryStageOutput) GetDebitWallet() *V2DebitWalletResponse {
	if o == nil {
		return nil
	}
	return o.DebitWallet
}

func (o *V2WorkflowInstanceHistoryStageOutput) GetGetWallet() *V2GetWalletResponse {
	if o == nil {
		return nil
	}
	return o.GetWallet
}

func (o *V2WorkflowInstanceHistoryStageOutput) GetListWallets() *V2ListWalletsResponse {
	if o == nil {
		return nil
	}
	return o.ListWallets
}
