// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type V2WorkflowInstanceHistoryStage struct {
	// Name of the activity this history entry records
	Name string `json:"name"`
	// Arguments an activity was called with, keyed by activity name
	Input V2WorkflowInstanceHistoryStageInput `json:"input"`
	// Result an activity returned, keyed by activity name
	Output *V2WorkflowInstanceHistoryStageOutput `json:"output,omitempty"`
	// Why the activity failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// Whether the activity has finished
	Terminated bool `json:"terminated"`
	// When the activity started
	StartedAt time.Time `json:"startedAt"`
	// When the activity finished, absent while it is still running
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`
	// Error reported by the most recent failed attempt
	LastFailure *string `json:"lastFailure,omitempty"`
	// How many times the activity has been attempted
	Attempt int64 `json:"attempt"`
	// When the next retry is scheduled, absent once the activity is settled
	NextExecution *time.Time `json:"nextExecution,omitempty"`
}

func (v V2WorkflowInstanceHistoryStage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2WorkflowInstanceHistoryStage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2WorkflowInstanceHistoryStage) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V2WorkflowInstanceHistoryStage) GetInput() V2WorkflowInstanceHistoryStageInput {
	if o == nil {
		return V2WorkflowInstanceHistoryStageInput{}
	}
	return o.Input
}

func (o *V2WorkflowInstanceHistoryStage) GetOutput() *V2WorkflowInstanceHistoryStageOutput {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *V2WorkflowInstanceHistoryStage) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *V2WorkflowInstanceHistoryStage) GetTerminated() bool {
	if o == nil {
		return false
	}
	return o.Terminated
}

func (o *V2WorkflowInstanceHistoryStage) GetStartedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartedAt
}

func (o *V2WorkflowInstanceHistoryStage) GetTerminatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.TerminatedAt
}

func (o *V2WorkflowInstanceHistoryStage) GetLastFailure() *string {
	if o == nil {
		return nil
	}
	return o.LastFailure
}

func (o *V2WorkflowInstanceHistoryStage) GetAttempt() int64 {
	if o == nil {
		return 0
	}
	return o.Attempt
}

func (o *V2WorkflowInstanceHistoryStage) GetNextExecution() *time.Time {
	if o == nil {
		return nil
	}
	return o.NextExecution
}
