// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// V2WorkflowInstance - One run of a workflow, tracking its per-stage progress
type V2WorkflowInstance struct {
	// Identifier of the workflow this run belongs to
	WorkflowID string `json:"workflowID"`
	// Unique identifier of the run
	ID string `json:"id"`
	// When the run was started
	CreatedAt time.Time `json:"createdAt"`
	// When the run was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// Per-stage progress of the run
	Status []V2StageStatus `json:"status,omitempty"`
	// Whether the run has finished, successfully or not
	Terminated bool `json:"terminated"`
	// When the run finished, absent while it is still running
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`
	// Why the run failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// A workflow definition and the stages it runs
	Workflow *V2Workflow `json:"workflow,omitempty"`
}

func (v V2WorkflowInstance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2WorkflowInstance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2WorkflowInstance) GetWorkflowID() string {
	if o == nil {
		return ""
	}
	return o.WorkflowID
}

func (o *V2WorkflowInstance) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V2WorkflowInstance) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *V2WorkflowInstance) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *V2WorkflowInstance) GetStatus() []V2StageStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *V2WorkflowInstance) GetTerminated() bool {
	if o == nil {
		return false
	}
	return o.Terminated
}

func (o *V2WorkflowInstance) GetTerminatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.TerminatedAt
}

func (o *V2WorkflowInstance) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *V2WorkflowInstance) GetWorkflow() *V2Workflow {
	if o == nil {
		return nil
	}
	return o.Workflow
}
