// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2WorkflowInstanceHistoryStageInput - Arguments an activity was called with, keyed by activity name
type V2WorkflowInstanceHistoryStageInput struct {
	// Arguments for the activity that reads a ledger account
	GetAccount *V2ActivityGetAccount `json:"GetAccount,omitempty"`
	// Arguments for the activity that sets metadata on a ledger account
	AddAccountMetadata *V2ActivityAddAccountMetadata `json:"AddAccountMetadata,omitempty"`
	// Arguments for the activity that writes a transaction to a ledger
	CreateTransaction *V2ActivityCreateTransaction `json:"CreateTransaction,omitempty"`
	// Arguments for the activity that transfers funds through Stripe
	StripeTransfer *V2StripeTransferRequest `json:"StripeTransfer,omitempty"`
	// Arguments for the activity that initiates a transfer through a connector
	CreateTransferInitiation *V2CreateTransferInitiationRequest `json:"CreateTransferInitiation,omitempty"`
	// Arguments for the activity that reads a payment
	GetPayment *V2ActivityGetPayment `json:"GetPayment,omitempty"`
	// Arguments for the activity that confirms a wallet hold
	ConfirmHold *V2ActivityConfirmHold `json:"ConfirmHold,omitempty"`
	// Arguments for the activity that credits a wallet
	CreditWallet *V2ActivityCreditWallet `json:"CreditWallet,omitempty"`
	// Arguments for the activity that debits a wallet
	DebitWallet *V2ActivityDebitWallet `json:"DebitWallet,omitempty"`
	// Arguments for the activity that reads a wallet
	GetWallet *V2ActivityGetWallet `json:"GetWallet,omitempty"`
	// Arguments for the activity that releases a wallet hold
	VoidHold *V2ActivityVoidHold `json:"VoidHold,omitempty"`
	// Arguments for the activity that lists wallets
	ListWallets *V2ActivityListWallets `json:"ListWallets,omitempty"`
}

func (o *V2WorkflowInstanceHistoryStageInput) GetGetAccount() *V2ActivityGetAccount {
	if o == nil {
		return nil
	}
	return o.GetAccount
}

func (o *V2WorkflowInstanceHistoryStageInput) GetAddAccountMetadata() *V2ActivityAddAccountMetadata {
	if o == nil {
		return nil
	}
	return o.AddAccountMetadata
}

func (o *V2WorkflowInstanceHistoryStageInput) GetCreateTransaction() *V2ActivityCreateTransaction {
	if o == nil {
		return nil
	}
	return o.CreateTransaction
}

func (o *V2WorkflowInstanceHistoryStageInput) GetStripeTransfer() *V2StripeTransferRequest {
	if o == nil {
		return nil
	}
	return o.StripeTransfer
}

func (o *V2WorkflowInstanceHistoryStageInput) GetCreateTransferInitiation() *V2CreateTransferInitiationRequest {
	if o == nil {
		return nil
	}
	return o.CreateTransferInitiation
}

func (o *V2WorkflowInstanceHistoryStageInput) GetGetPayment() *V2ActivityGetPayment {
	if o == nil {
		return nil
	}
	return o.GetPayment
}

func (o *V2WorkflowInstanceHistoryStageInput) GetConfirmHold() *V2ActivityConfirmHold {
	if o == nil {
		return nil
	}
	return o.ConfirmHold
}

func (o *V2WorkflowInstanceHistoryStageInput) GetCreditWallet() *V2ActivityCreditWallet {
	if o == nil {
		return nil
	}
	return o.CreditWallet
}

func (o *V2WorkflowInstanceHistoryStageInput) GetDebitWallet() *V2ActivityDebitWallet {
	if o == nil {
		return nil
	}
	return o.DebitWallet
}

func (o *V2WorkflowInstanceHistoryStageInput) GetGetWallet() *V2ActivityGetWallet {
	if o == nil {
		return nil
	}
	return o.GetWallet
}

func (o *V2WorkflowInstanceHistoryStageInput) GetVoidHold() *V2ActivityVoidHold {
	if o == nil {
		return nil
	}
	return o.VoidHold
}

func (o *V2WorkflowInstanceHistoryStageInput) GetListWallets() *V2ActivityListWallets {
	if o == nil {
		return nil
	}
	return o.ListWallets
}
