// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// Balances - Aggregated funds held by the wallet, keyed by asset
type Balances struct {
	Main AssetHolder `json:"main"`
}

func (o *Balances) GetMain() AssetHolder {
	if o == nil {
		return AssetHolder{}
	}
	return o.Main
}

// WalletWithBalances - A wallet together with the funds it currently holds
type WalletWithBalances struct {
	// The unique ID of the wallet.
	ID string `json:"id"`
	// Metadata associated with the wallet.
	Metadata map[string]string `json:"metadata"`
	// Human-readable name of the wallet
	Name string `json:"name"`
	// When the wallet was created
	CreatedAt time.Time `json:"createdAt"`
	// Aggregated funds held by the wallet, keyed by asset
	Balances Balances `json:"balances"`
	// Name of the ledger backing this wallet
	Ledger string `json:"ledger"`
}

func (w WalletWithBalances) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WalletWithBalances) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WalletWithBalances) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *WalletWithBalances) GetMetadata() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Metadata
}

func (o *WalletWithBalances) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *WalletWithBalances) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *WalletWithBalances) GetBalances() Balances {
	if o == nil {
		return Balances{}
	}
	return o.Balances
}

func (o *WalletWithBalances) GetLedger() string {
	if o == nil {
		return ""
	}
	return o.Ledger
}
