// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WorkflowInstanceHistoryStageInput - Arguments an activity was called with, keyed by activity name
type WorkflowInstanceHistoryStageInput struct {
	// Arguments for the activity that reads a ledger account
	GetAccount *ActivityGetAccount `json:"GetAccount,omitempty"`
	// Arguments for the activity that sets metadata on a ledger account
	AddAccountMetadata *ActivityAddAccountMetadata `json:"AddAccountMetadata,omitempty"`
	// Arguments for the activity that writes a transaction to a ledger
	CreateTransaction *ActivityCreateTransaction `json:"CreateTransaction,omitempty"`
	// Arguments for the activity that reverts a ledger transaction
	RevertTransaction *ActivityRevertTransaction `json:"RevertTransaction,omitempty"`
	// Arguments for the activity that transfers funds through Stripe
	StripeTransfer *StripeTransferRequest `json:"StripeTransfer,omitempty"`
	// Arguments for the activity that initiates a transfer through a connector
	CreateTransferInitiation *CreateTransferInitiationRequest `json:"CreateTransferInitiation,omitempty"`
	// Arguments for the activity that reads a payment
	GetPayment *ActivityGetPayment `json:"GetPayment,omitempty"`
	// Arguments for the activity that confirms a wallet hold
	ConfirmHold *ActivityConfirmHold `json:"ConfirmHold,omitempty"`
	// Arguments for the activity that credits a wallet
	CreditWallet *ActivityCreditWallet `json:"CreditWallet,omitempty"`
	// Arguments for the activity that debits a wallet
	DebitWallet *ActivityDebitWallet `json:"DebitWallet,omitempty"`
	// Arguments for the activity that reads a wallet
	GetWallet *ActivityGetWallet `json:"GetWallet,omitempty"`
	// Arguments for the activity that releases a wallet hold
	VoidHold *ActivityVoidHold `json:"VoidHold,omitempty"`
	// Arguments for the activity that lists wallets
	ListWallets *ActivityListWallets `json:"ListWallets,omitempty"`
}

func (o *WorkflowInstanceHistoryStageInput) GetGetAccount() *ActivityGetAccount {
	if o == nil {
		return nil
	}
	return o.GetAccount
}

func (o *WorkflowInstanceHistoryStageInput) GetAddAccountMetadata() *ActivityAddAccountMetadata {
	if o == nil {
		return nil
	}
	return o.AddAccountMetadata
}

func (o *WorkflowInstanceHistoryStageInput) GetCreateTransaction() *ActivityCreateTransaction {
	if o == nil {
		return nil
	}
	return o.CreateTransaction
}

func (o *WorkflowInstanceHistoryStageInput) GetRevertTransaction() *ActivityRevertTransaction {
	if o == nil {
		return nil
	}
	return o.RevertTransaction
}

func (o *WorkflowInstanceHistoryStageInput) GetStripeTransfer() *StripeTransferRequest {
	if o == nil {
		return nil
	}
	return o.StripeTransfer
}

func (o *WorkflowInstanceHistoryStageInput) GetCreateTransferInitiation() *CreateTransferInitiationRequest {
	if o == nil {
		return nil
	}
	return o.CreateTransferInitiation
}

func (o *WorkflowInstanceHistoryStageInput) GetGetPayment() *ActivityGetPayment {
	if o == nil {
		return nil
	}
	return o.GetPayment
}

func (o *WorkflowInstanceHistoryStageInput) GetConfirmHold() *ActivityConfirmHold {
	if o == nil {
		return nil
	}
	return o.ConfirmHold
}

func (o *WorkflowInstanceHistoryStageInput) GetCreditWallet() *ActivityCreditWallet {
	if o == nil {
		return nil
	}
	return o.CreditWallet
}

func (o *WorkflowInstanceHistoryStageInput) GetDebitWallet() *ActivityDebitWallet {
	if o == nil {
		return nil
	}
	return o.DebitWallet
}

func (o *WorkflowInstanceHistoryStageInput) GetGetWallet() *ActivityGetWallet {
	if o == nil {
		return nil
	}
	return o.GetWallet
}

func (o *WorkflowInstanceHistoryStageInput) GetVoidHold() *ActivityVoidHold {
	if o == nil {
		return nil
	}
	return o.VoidHold
}

func (o *WorkflowInstanceHistoryStageInput) GetListWallets() *ActivityListWallets {
	if o == nil {
		return nil
	}
	return o.ListWallets
}
