// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// Workflow - A workflow definition and the stages it runs
type Workflow struct {
	// The stages a workflow runs, in order
	Config WorkflowConfig `json:"config"`
	// When the workflow was created
	CreatedAt time.Time `json:"createdAt"`
	// When the workflow was last modified
	UpdatedAt time.Time `json:"updatedAt"`
	// Unique identifier of the workflow
	ID string `json:"id"`
}

func (w Workflow) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *Workflow) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Workflow) GetConfig() WorkflowConfig {
	if o == nil {
		return WorkflowConfig{}
	}
	return o.Config
}

func (o *Workflow) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Workflow) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *Workflow) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
