// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkflowInstanceHistoryStageOutput struct {
	GetAccount        *ActivityGetAccountOutput        `json:"GetAccount,omitempty"`
	CreateTransaction *ActivityCreateTransactionOutput `json:"CreateTransaction,omitempty"`
	RevertTransaction *ActivityRevertTransactionOutput `json:"RevertTransaction,omitempty"`
	GetPayment        *ActivityGetPaymentOutput        `json:"GetPayment,omitempty"`
	DebitWallet       *ActivityDebitWalletOutput       `json:"DebitWallet,omitempty"`
	GetWallet         *ActivityGetWalletOutput         `json:"GetWallet,omitempty"`
	ListWallets       *ListWalletsResponse             `json:"ListWallets,omitempty"`
}

func (o *WorkflowInstanceHistoryStageOutput) GetGetAccount() *ActivityGetAccountOutput {
	if o == nil {
		return nil
	}
	return o.GetAccount
}

func (o *WorkflowInstanceHistoryStageOutput) GetCreateTransaction() *ActivityCreateTransactionOutput {
	if o == nil {
		return nil
	}
	return o.CreateTransaction
}

func (o *WorkflowInstanceHistoryStageOutput) GetRevertTransaction() *ActivityRevertTransactionOutput {
	if o == nil {
		return nil
	}
	return o.RevertTransaction
}

func (o *WorkflowInstanceHistoryStageOutput) GetGetPayment() *ActivityGetPaymentOutput {
	if o == nil {
		return nil
	}
	return o.GetPayment
}

func (o *WorkflowInstanceHistoryStageOutput) GetDebitWallet() *ActivityDebitWalletOutput {
	if o == nil {
		return nil
	}
	return o.DebitWallet
}

func (o *WorkflowInstanceHistoryStageOutput) GetGetWallet() *ActivityGetWalletOutput {
	if o == nil {
		return nil
	}
	return o.GetWallet
}

func (o *WorkflowInstanceHistoryStageOutput) GetListWallets() *ListWalletsResponse {
	if o == nil {
		return nil
	}
	return o.ListWallets
}
