// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// WorkflowInstance - One run of a workflow, tracking its per-stage progress
type WorkflowInstance struct {
	// Identifier of the workflow this run belongs to
	WorkflowID string `json:"workflowID"`
	// Unique identifier of the run
	ID string `json:"id"`
	// When the run was started
	CreatedAt time.Time `json:"createdAt"`
	// When the run was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// Per-stage progress of the run
	Status []StageStatus `json:"status,omitempty"`
	// Whether the run has finished, successfully or not
	Terminated bool `json:"terminated"`
	// When the run finished, absent while it is still running
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`
	// Why the run failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// A workflow definition and the stages it runs
	Workflow *Workflow `json:"workflow,omitempty"`
}

func (w WorkflowInstance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkflowInstance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WorkflowInstance) GetWorkflowID() string {
	if o == nil {
		return ""
	}
	return o.WorkflowID
}

func (o *WorkflowInstance) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *WorkflowInstance) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *WorkflowInstance) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *WorkflowInstance) GetStatus() []StageStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *WorkflowInstance) GetTerminated() bool {
	if o == nil {
		return false
	}
	return o.Terminated
}

func (o *WorkflowInstance) GetTerminatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.TerminatedAt
}

func (o *WorkflowInstance) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *WorkflowInstance) GetWorkflow() *Workflow {
	if o == nil {
		return nil
	}
	return o.Workflow
}
