// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkflowInstanceHistoryStageInput struct {
	GetAccount         *ActivityGetAccount         `json:"GetAccount,omitempty"`
	AddAccountMetadata *ActivityAddAccountMetadata `json:"AddAccountMetadata,omitempty"`
	CreateTransaction  *ActivityCreateTransaction  `json:"CreateTransaction,omitempty"`
	RevertTransaction  *ActivityRevertTransaction  `json:"RevertTransaction,omitempty"`
	StripeTransfer     *ActivityStripeTransfer     `json:"StripeTransfer,omitempty"`
	GetPayment         *ActivityGetPayment         `json:"GetPayment,omitempty"`
	ConfirmHold        *ActivityConfirmHold        `json:"ConfirmHold,omitempty"`
	CreditWallet       *ActivityCreditWallet       `json:"CreditWallet,omitempty"`
	DebitWallet        *ActivityDebitWallet        `json:"DebitWallet,omitempty"`
	GetWallet          *ActivityGetWallet          `json:"GetWallet,omitempty"`
	VoidHold           *ActivityVoidHold           `json:"VoidHold,omitempty"`
	ListWallets        *ActivityListWallets        `json:"ListWallets,omitempty"`
}

func (o *WorkflowInstanceHistoryStageInput) GetGetAccount() *ActivityGetAccount {
	if o == nil {
		return nil
	}
	return o.GetAccount
}

func (o *WorkflowInstanceHistoryStageInput) GetAddAccountMetadata() *ActivityAddAccountMetadata {
	if o == nil {
		return nil
	}
	return o.AddAccountMetadata
}

func (o *WorkflowInstanceHistoryStageInput) GetCreateTransaction() *ActivityCreateTransaction {
	if o == nil {
		return nil
	}
	return o.CreateTransaction
}

func (o *WorkflowInstanceHistoryStageInput) GetRevertTransaction() *ActivityRevertTransaction {
	if o == nil {
		return nil
	}
	return o.RevertTransaction
}

func (o *WorkflowInstanceHistoryStageInput) GetStripeTransfer() *ActivityStripeTransfer {
	if o == nil {
		return nil
	}
	return o.StripeTransfer
}

func (o *WorkflowInstanceHistoryStageInput) GetGetPayment() *ActivityGetPayment {
	if o == nil {
		return nil
	}
	return o.GetPayment
}

func (o *WorkflowInstanceHistoryStageInput) GetConfirmHold() *ActivityConfirmHold {
	if o == nil {
		return nil
	}
	return o.ConfirmHold
}

func (o *WorkflowInstanceHistoryStageInput) GetCreditWallet() *ActivityCreditWallet {
	if o == nil {
		return nil
	}
	return o.CreditWallet
}

func (o *WorkflowInstanceHistoryStageInput) GetDebitWallet() *ActivityDebitWallet {
	if o == nil {
		return nil
	}
	return o.DebitWallet
}

func (o *WorkflowInstanceHistoryStageInput) GetGetWallet() *ActivityGetWallet {
	if o == nil {
		return nil
	}
	return o.GetWallet
}

func (o *WorkflowInstanceHistoryStageInput) GetVoidHold() *ActivityVoidHold {
	if o == nil {
		return nil
	}
	return o.VoidHold
}

func (o *WorkflowInstanceHistoryStageInput) GetListWallets() *ActivityListWallets {
	if o == nil {
		return nil
	}
	return o.ListWallets
}
