// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type WorkflowInstanceHistoryStage struct {
	// Stable identifier of the activity within its workflow execution
	ActivityID *string `json:"activityID,omitempty"`
	// Run identifier of the described stage workflow execution
	TemporalRunID *string `json:"temporalRunID,omitempty"`
	// Whether Temporal has paused this pending activity; a pause is not a terminal failure
	Paused *bool `json:"paused,omitempty"`
	// Reason recorded by Temporal for the activity pause, when available
	PauseReason *string `json:"pauseReason,omitempty"`
	// Application failure type of the most recent failed attempt, when available
	LastFailureType *string `json:"lastFailureType,omitempty"`
	// Name of the activity this history entry records
	Name string `json:"name"`
	// Arguments an activity was called with, keyed by activity name
	Input WorkflowInstanceHistoryStageInput `json:"input"`
	// Result an activity returned, keyed by activity name
	Output *WorkflowInstanceHistoryStageOutput `json:"output,omitempty"`
	// Why the activity failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// Whether the activity has finished
	Terminated bool `json:"terminated"`
	// When the activity started
	StartedAt time.Time `json:"startedAt"`
	// When the activity finished, absent while it is still running
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`
	// Error reported by the most recent failed attempt
	LastFailure *string `json:"lastFailure,omitempty"`
	// How many times the activity has been attempted
	Attempt int64 `json:"attempt"`
	// When the next retry is scheduled, absent while paused, when no retry is scheduled, or once settled
	NextExecution *time.Time `json:"nextExecution,omitempty"`
}

func (w WorkflowInstanceHistoryStage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkflowInstanceHistoryStage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WorkflowInstanceHistoryStage) GetActivityID() *string {
	if o == nil {
		return nil
	}
	return o.ActivityID
}

func (o *WorkflowInstanceHistoryStage) GetTemporalRunID() *string {
	if o == nil {
		return nil
	}
	return o.TemporalRunID
}

func (o *WorkflowInstanceHistoryStage) GetPaused() *bool {
	if o == nil {
		return nil
	}
	return o.Paused
}

func (o *WorkflowInstanceHistoryStage) GetPauseReason() *string {
	if o == nil {
		return nil
	}
	return o.PauseReason
}

func (o *WorkflowInstanceHistoryStage) GetLastFailureType() *string {
	if o == nil {
		return nil
	}
	return o.LastFailureType
}

func (o *WorkflowInstanceHistoryStage) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *WorkflowInstanceHistoryStage) GetInput() WorkflowInstanceHistoryStageInput {
	if o == nil {
		return WorkflowInstanceHistoryStageInput{}
	}
	return o.Input
}

func (o *WorkflowInstanceHistoryStage) GetOutput() *WorkflowInstanceHistoryStageOutput {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *WorkflowInstanceHistoryStage) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *WorkflowInstanceHistoryStage) GetTerminated() bool {
	if o == nil {
		return false
	}
	return o.Terminated
}

func (o *WorkflowInstanceHistoryStage) GetStartedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartedAt
}

func (o *WorkflowInstanceHistoryStage) GetTerminatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.TerminatedAt
}

func (o *WorkflowInstanceHistoryStage) GetLastFailure() *string {
	if o == nil {
		return nil
	}
	return o.LastFailure
}

func (o *WorkflowInstanceHistoryStage) GetAttempt() int64 {
	if o == nil {
		return 0
	}
	return o.Attempt
}

func (o *WorkflowInstanceHistoryStage) GetNextExecution() *time.Time {
	if o == nil {
		return nil
	}
	return o.NextExecution
}
