// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type WorkflowInstanceHistory struct {
	// Name of the stage this history entry records
	Name string `json:"name"`
	// One step of a workflow, whose shape depends on the stage type
	Input Stage `json:"input"`
	// Why the stage failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// Whether the stage has finished
	Terminated bool `json:"terminated"`
	// When the stage started
	StartedAt time.Time `json:"startedAt"`
	// When the stage finished, absent while it is still running
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`
}

func (w WorkflowInstanceHistory) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkflowInstanceHistory) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WorkflowInstanceHistory) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *WorkflowInstanceHistory) GetInput() Stage {
	if o == nil {
		return Stage{}
	}
	return o.Input
}

func (o *WorkflowInstanceHistory) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *WorkflowInstanceHistory) GetTerminated() bool {
	if o == nil {
		return false
	}
	return o.Terminated
}

func (o *WorkflowInstanceHistory) GetStartedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartedAt
}

func (o *WorkflowInstanceHistory) GetTerminatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.TerminatedAt
}
