package audit

import (
	"fmt"
	"sort"
	"strings"
)

// Markdown renders the generated half of the inventory: the totals table, the
// per-family operation tables, and the baseline mapping table. The reasoning,
// evidence and gate discussion live in the hand-written inventory document,
// which links to this file.
func (r *Report) Markdown() string {
	var b strings.Builder

	b.WriteString("<!-- Code generated by plugins/fctl/cmd/specaudit; DO NOT EDIT. -->\n\n")
	b.WriteString("# Flows (orchestration) operation inventory (generated)\n\n")
	fmt.Fprintf(&b, "Source document: `%s` (repository root)\n\n", r.SpecDocument)
	fmt.Fprintf(&b, "Orchestration revision: `%s`\n\n", r.ProductRevision)
	fmt.Fprintf(&b, "Legacy fctl baseline revision: `%s`\n\n", r.BaselineRevision)

	b.WriteString("## Totals\n\n")
	b.WriteString("| Count | Value |\n|---|---:|\n")
	t := r.Totals
	for _, row := range [][2]any{
		{"Operations in document (both majors)", t.SpecOperations},
		{"Unique operationIds", t.UniqueOperationIDs},
		{"`orchestration.v1` operations", t.V1Operations},
		{"`orchestration.v2` operations", t.V2Operations},
		{"Operations marked deprecated", t.DeprecatedOperations},
		{"Legacy fctl `orchestration` commands (executable leaves)", t.BaselineCommands},
		{"Legacy commands mapped onto an operation", t.BaselineMapped},
		{"Legacy commands excluded with evidence", t.BaselineExcluded},
		{"Distinct operations the legacy baseline reaches", t.BaselineDistinctOperations},
		{"Operations reached by the legacy baseline", t.WithBaseline},
		{"Operations with no legacy precedent", t.WithoutBaseline},
		{"Operations carrying a blocker", t.Blocked},
		{"Operations with no recorded blocker", t.Unblocked},
		{"Operations declaring cursor pagination", t.PaginatedOperations},
		{"Operations returning an unbounded collection", t.UnboundedCollections},
		{"Operations using a state-changing method", t.MutatingOperations},
		{"Operations that remove or terminate state", t.DestructiveOperations},
	} {
		fmt.Fprintf(&b, "| %v | %v |\n", row[0], row[1])
	}

	b.WriteString("\n## Operations by family\n\n")
	groups := r.ByFamily()
	families := make([]Family, 0, len(groups))
	for f := range groups {
		families = append(families, f)
	}
	sort.Slice(families, func(i, j int) bool { return families[i] < families[j] })

	for _, f := range families {
		fmt.Fprintf(&b, "### %s (%d)\n\n", f, len(groups[f]))
		b.WriteString("| operationId | SDK method | Major | Method | Path | Scopes | Request | Success | Risk | Legacy command(s) | Blockers |\n")
		b.WriteString("|---|---|---|---|---|---|---|---|---|---|---|\n")
		for _, rec := range groups[f] {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s | `%s` | %s | %s | %s | %s | %s | %s |\n",
				rec.OperationID,
				rec.SDKMethod,
				rec.Version,
				rec.Method,
				rec.Path,
				scopeCell(rec.Operation),
				bodyCell(rec.RequestBody),
				successCell(rec.Operation),
				riskCell(rec.Risk),
				commandCell(rec.BaselineCommands),
				listCell(rec.Blockers),
			)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Legacy baseline mapping\n\n")
	b.WriteString("| Legacy command | Source file | SDK call(s) | operationId(s) |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, c := range Baseline {
		target := "— (excluded)"
		if len(c.Ops) > 0 {
			target = codeList(c.Ops)
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n",
			escapeCell(c.Path), c.SourceFile, codeList(c.SDKCalls), target)
	}

	b.WriteString("\n## Operations with no legacy precedent\n\n")
	b.WriteString("| operationId | Major | Method | Path | Blockers |\n|---|---|---|---|---|\n")
	for _, rec := range r.Operations {
		if len(rec.BaselineCommands) > 0 {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | `%s` | %s |\n",
			rec.OperationID, rec.Version, rec.Method, rec.Path, listCell(rec.Blockers))
	}

	b.WriteString("\n## Blockers\n\n")
	for _, blocker := range Blockers {
		fmt.Fprintf(&b, "### %s (%s)\n\n", blocker.ID, pluralOperations(len(blocker.OperationIDs)))
		fmt.Fprintf(&b, "%s\n\n", blocker.Summary)
		fmt.Fprintf(&b, "**Evidence.** %s\n\n", blocker.Evidence)
		if blocker.Reproduce != "" {
			b.WriteString("**Reproduce.**\n\n```sh\n" + blocker.Reproduce + "\n```\n\n")
		}
	}

	b.WriteString("## Spec-versus-server divergences\n\n")
	for _, d := range Divergences {
		fmt.Fprintf(&b, "### %s\n\n%s\n\n**Evidence.** %s\n\n", d.ID, d.Summary, d.Evidence)
	}

	b.WriteString("## Deprecated operations in the document\n\n")
	var deprecated int
	for _, rec := range r.Operations {
		if rec.Deprecated {
			if deprecated == 0 {
				b.WriteString("| operationId | Major | Method | Path |\n|---|---|---|---|\n")
			}
			deprecated++
			fmt.Fprintf(&b, "| `%s` | %s | %s | `%s` |\n", rec.OperationID, rec.Version, rec.Method, rec.Path)
		}
	}
	if deprecated == 0 {
		b.WriteString("None. The document marks no operation `deprecated` in either major.\n")
	}

	return b.String()
}

func pluralOperations(n int) string {
	if n == 1 {
		return "1 operation"
	}
	return fmt.Sprintf("%d operations", n)
}

func scopeCell(op Operation) string {
	if !op.HasSecurity {
		return "**none declared**"
	}
	if len(op.Scopes) == 0 {
		return "`[]`"
	}
	return codeList(op.Scopes)
}

func bodyCell(name string) string {
	switch name {
	case "":
		return "—"
	case InlineSchema:
		return name
	default:
		return "`" + name + "`"
	}
}

func successCell(op Operation) string {
	if op.SuccessBody == "" {
		return op.SuccessCode + " (no body)"
	}
	return op.SuccessCode + " `" + op.SuccessBody + "`"
}

func riskCell(r Risk) string {
	var tags []string
	if r.Destructive {
		tags = append(tags, "destructive")
	}
	switch r.Secret {
	case SecretInbound:
		tags = append(tags, "secret:request")
	case SecretOutbound:
		tags = append(tags, "secret:response")
	}
	if r.DisplayOnce {
		tags = append(tags, "display-once")
	}
	if r.EchoesUserExpressions {
		tags = append(tags, "user-expressions")
	}
	if r.LongRunning {
		tags = append(tags, "long-running")
	}
	if r.UnboundedCollection {
		tags = append(tags, "unbounded")
	}
	if r.Paginated {
		tags = append(tags, "paginated")
	}
	if !r.ReplaySafe {
		tags = append(tags, "not-replay-safe")
	}
	if len(tags) == 0 {
		return "—"
	}
	return strings.Join(tags, ", ")
}

func commandCell(paths []string) string {
	if len(paths) == 0 {
		return "— (no legacy precedent)"
	}
	return codeList(paths)
}

func listCell(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	return strings.Join(items, ", ")
}

func codeList(items []string) string {
	quoted := make([]string, 0, len(items))
	for _, s := range items {
		quoted = append(quoted, "`"+escapeCell(s)+"`")
	}
	return strings.Join(quoted, "<br>")
}

// escapeCell escapes the pipes that legacy command paths carry (`<file>|-`), so
// they do not terminate the table cell they are rendered in.
func escapeCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
