// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type CreateWorkflowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created workflow
	CreateWorkflowResponse *components.CreateWorkflowResponse
}

func (o *CreateWorkflowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateWorkflowResponse) GetCreateWorkflowResponse() *components.CreateWorkflowResponse {
	if o == nil {
		return nil
	}
	return o.CreateWorkflowResponse
}
