// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type CreateTriggerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created trigger
	CreateTriggerResponse *components.CreateTriggerResponse
}

func (o *CreateTriggerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateTriggerResponse) GetCreateTriggerResponse() *components.CreateTriggerResponse {
	if o == nil {
		return nil
	}
	return o.CreateTriggerResponse
}
