// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetInstanceHistoryRequest struct {
	// The instance id
	InstanceID string `pathParam:"style=simple,explode=false,name=instanceID"`
}

func (o *GetInstanceHistoryRequest) GetInstanceID() string {
	if o == nil {
		return ""
	}
	return o.InstanceID
}

type GetInstanceHistoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The workflow instance history
	GetWorkflowInstanceHistoryResponse *components.GetWorkflowInstanceHistoryResponse
}

func (o *GetInstanceHistoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetInstanceHistoryResponse) GetGetWorkflowInstanceHistoryResponse() *components.GetWorkflowInstanceHistoryResponse {
	if o == nil {
		return nil
	}
	return o.GetWorkflowInstanceHistoryResponse
}
