// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetInstanceRequest struct {
	// The instance id
	InstanceID string `pathParam:"style=simple,explode=false,name=instanceID"`
}

func (o *GetInstanceRequest) GetInstanceID() string {
	if o == nil {
		return ""
	}
	return o.InstanceID
}

type GetInstanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The workflow instance
	GetWorkflowInstanceResponse *components.GetWorkflowInstanceResponse
}

func (o *GetInstanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetInstanceResponse) GetGetWorkflowInstanceResponse() *components.GetWorkflowInstanceResponse {
	if o == nil {
		return nil
	}
	return o.GetWorkflowInstanceResponse
}
