// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/flows/pkg/client/internal/utils"
	"github.com/formancehq/flows/pkg/client/models/components"
)

type ListInstancesRequest struct {
	// A workflow id
	WorkflowID *string `queryParam:"style=form,explode=true,name=workflowID"`
	// Filter running instances
	Running *bool `queryParam:"style=form,explode=true,name=running"`
	// The maximum number of results to return per page.
	//
	PageSize *int64 `default:"15" queryParam:"style=form,explode=true,name=pageSize"`
	// Parameter used in pagination requests.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListInstancesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInstancesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListInstancesRequest) GetWorkflowID() *string {
	if o == nil {
		return nil
	}
	return o.WorkflowID
}

func (o *ListInstancesRequest) GetRunning() *bool {
	if o == nil {
		return nil
	}
	return o.Running
}

func (o *ListInstancesRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListInstancesRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListInstancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of workflow instances
	ListRunsResponse *components.ListRunsResponse
}

func (o *ListInstancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListInstancesResponse) GetListRunsResponse() *components.ListRunsResponse {
	if o == nil {
		return nil
	}
	return o.ListRunsResponse
}
