// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/flows/pkg/client/internal/utils"
	"github.com/formancehq/flows/pkg/client/models/components"
)

type ListWorkflowsRequest struct {
	// The maximum number of results to return per page.
	//
	PageSize *int64 `default:"15" queryParam:"style=form,explode=true,name=pageSize"`
	// Parameter used in pagination requests.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListWorkflowsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListWorkflowsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListWorkflowsRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListWorkflowsRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListWorkflowsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of workflows
	ListWorkflowsResponse *components.ListWorkflowsResponse
}

func (o *ListWorkflowsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListWorkflowsResponse) GetListWorkflowsResponse() *components.ListWorkflowsResponse {
	if o == nil {
		return nil
	}
	return o.ListWorkflowsResponse
}
