// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type ListInstancesRequest struct {
	// A workflow id
	WorkflowID *string `queryParam:"style=form,explode=true,name=workflowID"`
	// Filter running instances
	Running *bool `queryParam:"style=form,explode=true,name=running"`
}

func (o *ListInstancesRequest) GetWorkflowID() *string {
	if o == nil {
		return nil
	}
	return o.WorkflowID
}

func (o *ListInstancesRequest) GetRunning() *bool {
	if o == nil {
		return nil
	}
	return o.Running
}

type ListInstancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of workflow instances
	ListRunsResponse *components.ListRunsResponse
}

func (o *ListInstancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListInstancesResponse) GetListRunsResponse() *components.ListRunsResponse {
	if o == nil {
		return nil
	}
	return o.ListRunsResponse
}
