// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/utils"
	"openapi/models/components"
	"openapi/models/sdkerrors"
	"time"
)

type ResumeActivityRequestBody struct {
	// Expected Temporal run id from the paused activity projection
	TemporalRunID string `json:"temporalRunID"`
	// Nonzero RFC3339 timestamp from the paused activity projection identifying the pause generation
	PausedAt time.Time `json:"pausedAt"`
}

func (r ResumeActivityRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResumeActivityRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ResumeActivityRequestBody) GetTemporalRunID() string {
	if o == nil {
		return ""
	}
	return o.TemporalRunID
}

func (o *ResumeActivityRequestBody) GetPausedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.PausedAt
}

type ResumeActivityRequest struct {
	// The instance id
	InstanceID string `pathParam:"style=simple,explode=false,name=instanceID"`
	// The nonnegative stage number
	Number int64 `pathParam:"style=simple,explode=false,name=number"`
	// The paused activity id
	ActivityID  string                    `pathParam:"style=simple,explode=false,name=activityID"`
	RequestBody ResumeActivityRequestBody `request:"mediaType=application/json"`
}

func (o *ResumeActivityRequest) GetInstanceID() string {
	if o == nil {
		return ""
	}
	return o.InstanceID
}

func (o *ResumeActivityRequest) GetNumber() int64 {
	if o == nil {
		return 0
	}
	return o.Number
}

func (o *ResumeActivityRequest) GetActivityID() string {
	if o == nil {
		return ""
	}
	return o.ActivityID
}

func (o *ResumeActivityRequest) GetRequestBody() ResumeActivityRequestBody {
	if o == nil {
		return ResumeActivityRequestBody{}
	}
	return o.RequestBody
}

type ResumeActivityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// General error
	Error *sdkerrors.Error
}

func (o *ResumeActivityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ResumeActivityResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
