// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type SendEventRequestBody struct {
	Name string `json:"name"`
}

func (o *SendEventRequestBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

type SendEventRequest struct {
	// The instance id
	InstanceID  string                `pathParam:"style=simple,explode=false,name=instanceID"`
	RequestBody *SendEventRequestBody `request:"mediaType=application/json"`
}

func (o *SendEventRequest) GetInstanceID() string {
	if o == nil {
		return ""
	}
	return o.InstanceID
}

func (o *SendEventRequest) GetRequestBody() *SendEventRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type SendEventResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *SendEventResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
