// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type TestTriggerRequest struct {
	// The trigger id
	TriggerID   string         `pathParam:"style=simple,explode=false,name=triggerID"`
	RequestBody map[string]any `request:"mediaType=application/json"`
}

func (o *TestTriggerRequest) GetTriggerID() string {
	if o == nil {
		return ""
	}
	return o.TriggerID
}

func (o *TestTriggerRequest) GetRequestBody() map[string]any {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type TestTriggerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Test a trigger
	V2TestTriggerResponse *components.V2TestTriggerResponse
}

func (o *TestTriggerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TestTriggerResponse) GetV2TestTriggerResponse() *components.V2TestTriggerResponse {
	if o == nil {
		return nil
	}
	return o.V2TestTriggerResponse
}
