// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/flows/pkg/client/internal/utils"
	"github.com/formancehq/flows/pkg/client/models/components"
)

type V2ListTriggersOccurrencesRequest struct {
	// The trigger id
	TriggerID string `pathParam:"style=simple,explode=false,name=triggerID"`
	// Parameter used in pagination requests.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The maximum number of results to return per page.
	//
	PageSize *int64 `default:"15" queryParam:"style=form,explode=true,name=pageSize"`
}

func (v V2ListTriggersOccurrencesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2ListTriggersOccurrencesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2ListTriggersOccurrencesRequest) GetTriggerID() string {
	if o == nil {
		return ""
	}
	return o.TriggerID
}

func (o *V2ListTriggersOccurrencesRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *V2ListTriggersOccurrencesRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type V2ListTriggersOccurrencesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of triggers occurrences
	V2ListTriggersOccurrencesResponse *components.V2ListTriggersOccurrencesResponse
}

func (o *V2ListTriggersOccurrencesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V2ListTriggersOccurrencesResponse) GetV2ListTriggersOccurrencesResponse() *components.V2ListTriggersOccurrencesResponse {
	if o == nil {
		return nil
	}
	return o.V2ListTriggersOccurrencesResponse
}
