// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/utils"
	"openapi/models/components"
	"openapi/models/sdkerrors"
	"time"
)

type V2ResumeActivityRequestBody struct {
	// Expected Temporal run id from the paused activity projection
	TemporalRunID string `json:"temporalRunID"`
	// Nonzero RFC3339 timestamp from the paused activity projection identifying the pause generation
	PausedAt time.Time `json:"pausedAt"`
}

func (v V2ResumeActivityRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2ResumeActivityRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V2ResumeActivityRequestBody) GetTemporalRunID() string {
	if o == nil {
		return ""
	}
	return o.TemporalRunID
}

func (o *V2ResumeActivityRequestBody) GetPausedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.PausedAt
}

type V2ResumeActivityRequest struct {
	// The instance id
	InstanceID string `pathParam:"style=simple,explode=false,name=instanceID"`
	// The nonnegative stage number
	Number int64 `pathParam:"style=simple,explode=false,name=number"`
	// The paused activity id
	ActivityID  string                      `pathParam:"style=simple,explode=false,name=activityID"`
	RequestBody V2ResumeActivityRequestBody `request:"mediaType=application/json"`
}

func (o *V2ResumeActivityRequest) GetInstanceID() string {
	if o == nil {
		return ""
	}
	return o.InstanceID
}

func (o *V2ResumeActivityRequest) GetNumber() int64 {
	if o == nil {
		return 0
	}
	return o.Number
}

func (o *V2ResumeActivityRequest) GetActivityID() string {
	if o == nil {
		return ""
	}
	return o.ActivityID
}

func (o *V2ResumeActivityRequest) GetRequestBody() V2ResumeActivityRequestBody {
	if o == nil {
		return V2ResumeActivityRequestBody{}
	}
	return o.RequestBody
}

type V2ResumeActivityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// General error
	V2Error *sdkerrors.V2Error
}

func (o *V2ResumeActivityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V2ResumeActivityResponse) GetV2Error() *sdkerrors.V2Error {
	if o == nil {
		return nil
	}
	return o.V2Error
}
