// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package openapi

type Orchestration struct {
	V1 *V1
	V2 *V2

	sdkConfiguration sdkConfiguration
}

func newOrchestration(sdkConfig sdkConfiguration) *Orchestration {
	return &Orchestration{
		sdkConfiguration: sdkConfig,
		V1:               newV1(sdkConfig),
		V2:               newV2(sdkConfig),
	}
}
